### ISSUE TITLE
"Create multi-capability app" link in Search ME template goes to 404

### ISSUE THREAD

**Issue by AE-MS** [OfficeDev/teams-toolkit#10032]
**To Reproduce**
Using TTK 5.2.0

1. Create a new Search ME
2. In the preview of README.MD, scroll down to the "Extend the template" section
3. Click on the link for "Create multi-capability app"
4. It launches a browser to https://learn.microsoft.com/en-us/msteams-platform/toolkit/toolkit-v4/add-capability-v4, which is a 404 page.

**Screenshots**
<img width="866" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/36546967/5bc322e0-e537-4010-98e7-8ab9b16bb54a">

**Comment by yukun-dong** [comment]
@AE-MS thanks for reporting this issue.
This a issue from doc site. We will discuss later for how to fix this. For now, you can go to https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/toolkit-v4/add-capability-v4 which is the correct link for the doc.
