### ISSUE TITLE
Teams Bot On Add Experience

### ISSUE THREAD

**Issue by msdev512** [OfficeDev/teams-toolkit#10137]
Hi,

I need to Save some "Custom Configurations" for Bot App  On adding it in teams environment.
Please also suggest the recommended storage location for Bot App Custom Configuration.( e.g. API Key )

I found an official documentation reference given below but this sample code is not working please help.

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bot-configuration-experience#code-sample

Thank & Best Regards,

**Comment by MuyangAmigo** [comment]
Hey @msdev512 we are investigating this issue, will update as soon as we find anything

**Comment by a1exwang** [comment]
The [sample app](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-configuration-app/nodejs/demo-manifest) doesn't work for me either. Still not working after I enable the Teams developer preview flag. Probably a upstream issue.

The configuration page doesn't show up when adding app to a channel and there is no gear icon when hovering the bot.
![image](https://github.com/OfficeDev/TeamsFx/assets/9698542/416a018f-3ef4-4445-9ae1-88483418fdf9)

**Comment by a1exwang** [comment]
@Wajeed-msft could you take a look?

**Comment by msdev512** [comment]
Hello,

Can you please help on this?

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/9726

**Comment by MuyangAmigo** [comment]
Close as issue has been copied over.
