### ISSUE TITLE
Unable to stretch Input.Text

### ISSUE THREAD

**Issue by Neronuser** [OfficeDev/teams-toolkit#10206]
**Describe the bug**
Input.Text item with height: "stretch" should stretch parent container with certain minHeight. The attached adaptive card works on adaptivecards.io and in VS code card preview, but does not work while testing locally through VS Code Teams Toolkit.

**To Reproduce**
1. Create an MS Teams bot with the following adaptive card
```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "Input.Text",
                    "id": "answer",
                    "isMultiline": true,
                    "isRequired": true,
                    "placeholder": "Input here",
                    "value": "Test",
                    "label": "Please input your text here",
                    "errorMessage": "Answer is required",
                    "height": "stretch"
                }
            ],
            "minHeight": "400px"
        }
    ],
    "msteams": {
        "width": "Full"
    },
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}
```
2. Preview your teams app
3. Trigger the adaptive card

**Expected behavior**
The input form stretches its parent container

**Screenshots**
This is how it's rendered currently
<img width="653" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/8417184/9264254d-ca10-4785-b938-ca3b2039fae1">

**VS Code Extension Information (please complete the following information):**
 - OS: MacOS Ventura 13.3.1 (a)
 - Version 5.2.0

**Comment by dooriya** [comment]
This issue has been resolved in the Teams Client, so I’ll close it here.
![image](https://github.com/user-attachments/assets/026eec10-4bc6-4b43-9b1a-e19080dca58f)
