### ISSUE TITLE
Error handling request: Failed to decrypt conversation id

### ISSUE THREAD

**Issue by abdalrahman-alhmouz** [OfficeDev/teams-toolkit#10847]
I am creating a bot in Microsoft teams by developer portal, which the bot is connected to azure, the test in web chat in azure is working fine and reflecting the response, but the microsoft teams bot throwing this error Error handling request: Failed to decrypt conversation id

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/10347

**Comment by MuyangAmigo** [comment]
Close as issue has been copied over.
