### ISSUE TITLE
botAadApp/create failed: CredentialInvalidLifetimeAsPerAppPolicy

### ISSUE THREAD

**Issue by ross-p-smith** [OfficeDev/teams-toolkit#10998]
**Describe the bug**
When I Provision an application it fails 

```
  (×) Error: botAadApp/create failed.
    (×) Error: A http client error happened while performing the botAadApp/create task. The error response is: {"error":{"code":"CredentialInvalidLifetimeAsPerAppPolicy","message":"Credential lifetime exceeds the max value allowed as per assigned policy 'aaaaaaa'.","details":[{"code":"InvalidKeyEndDate","message":"Credential lifetime exceeds the max value allowed as per assigned policy 'aaaaaa'.","target":"EndDate"}],"innerError":{"date":"2024-03-05T13:14:55","request-id":"xxxx","client-request-id":"xxxx"}}}
```

**Expected behavior**
Documentation should tell me how to set the Credential Lifetime or how to set this up manually

**VS Code Extension Information (please complete the following information):**
 - OS: WSL
 - Version latest

**Comment by blackchoey** [comment]
@ross-p-smith We're working to support setting customized credential lifetime for you application. For now, please follow [Use an existing Microsoft Entra app for your bot](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision?pivots=visual-studio-code-v5#use-an-existing-microsoft-entra-app-for-your-bot) to create an app by yourself and use it in your project.

**Comment by blackchoey** [comment]
The latest Teams Toolkit is able to set customized credential lifetime via `aadApp/create` action now. Please have a try and let us know if you have further questions.
