### ISSUE TITLE
Action required to prepare your app for cloud.microsoft by June 2024

### ISSUE THREAD

**Issue by georgemichailou** [OfficeDev/teams-toolkit#11224]
**Is your feature request related to a problem? Please describe.**

In order to avoid any breaking changes to your app in the new (cloud.microsoft)domain, you will need to perform the following actions prior to June 2024:
1.	Upgrade to version 2.19 or above of the [Teams JS library](https://www.npmjs.com/package/@microsoft/teams-js)
2.	Retain the domains that your app’s CSP headers/ x-frame-options currently refer to
3.	Update your x-frame-options/CSP headers to allow for  add:
a.	*.cloud.microsoft.com

**Describe the solution you'd like**
Can you inform us with the steps that need to follow to achieve this upgrade ?

**Additional context**
[Developer Blog Post](https://devblogs.microsoft.com/microsoft365dev/action-required-ensure-your-microsoft-teams-apps-are-ready-for-upcoming-domain-changes/)

**Comment by MuyangAmigo** [comment]
Hey @georgemichailou, Thank you for bringing this into our attention. We are formalizing a plan to update our samples and app templates to prepare for the domain change as well as a migration / upgrade support for any existing projects.

**Comment by MuyangAmigo** [comment]
Hey @georgemichailou , we are evaluating if there's a need to update our SDKs, will keep you posted. But it's always good to use the latest stable version available.

**Comment by therealjohn** [comment]
We've updated the packages to bump the TeamsJS dependency and is available: 
https://www.npmjs.com/package/@microsoft/teamsfx-react/v/3.1.2-alpha.2c983f96a.0
https://www.npmjs.com/package/@microsoft/teamsfx/v/2.3.2-alpha.2c983f96a.0
https://www.nuget.org/packages/Microsoft.TeamsFx/2.4.1-rc

**Comment by georgemichailou** [comment]
@therealjohn i complete migration steps from v1.0.0 to 2.4.0 but i recieve the following error 

![image](https://github.com/OfficeDev/TeamsFx/assets/14372162/a8af0ea7-1c0e-41a2-9d37-98bfe61c76c8)

**Comment by georgemichailou** [comment]
Please update TeamsJsBlazorInterop.js in samples with inTeams function
 [in](https://github.com/OfficeDev/TeamsFx/issues/4365)

**Comment by MuyangAmigo** [comment]
> Please update TeamsJsBlazorInterop.js in samples with inTeams function [in](https://github.com/OfficeDev/TeamsFx/issues/4365)

Hey @georgemichailou, which sample are you referring to?
