### ISSUE TITLE
Select V2 of Teams

### ISSUE THREAD

**Issue by pkbullock** [OfficeDev/teams-toolkit#11466]
**Is your feature request related to a problem? Please describe.**

I am using InPrivate mode, and would like to specify the V2 Teams Client, just wondering if that can be specified in the launch.json somewhere, I cannot figure it out. Wondered if folks knew?

This is when debugging in Teams Toolkit. For some reason this is prompting to switch to V2 of the client. Ill see if this is a Team Admin switch too.

**Comment by blackchoey** [comment]
@pkbullock Teams stores something in your bowser's storage to tell itself which version of Teams Client to be opened. If you want to use V2 Teams Client, please follow below steps:
1. Start debugging your Teams app
2. Switch to V2 Teams Client in the opened Teams Web Client
3. Stop debugging and start debugging again
4. The opened Teams Web Client would be V2 now

**Comment by therealjohn** [comment]
If you want to force v2, you may be able to modify the URL in launch.json to have `/v2` in it like this: 

`"url": "https://teams.microsoft.com/v2/l/app/${{local:TEAMS_APP_ID}}?installAppPackage=true&webjoin=true&${account-hint}",`
