### ISSUE TITLE
TeamsFx Binding in Azure Functions Node v4 

### ISSUE THREAD

**Issue by ThomasPe** [OfficeDev/teams-toolkit#11569]
**Is your feature request related to a problem? Please describe.**
I'm using the latest fluent ui + api starter and am wondering about the missing TeamsFx binding for functions. Is this supported / even possible with the v4 model? The included sample does create an OnBehalfOfUserCredential, is that the easiest way to simply get the user id & tenant id?

**Comment by blackchoey** [comment]
@ThomasPe Azure Function has added feature that provided by TeamsFx binding previously. So you don't need to add TeamsFx binding anymore.
You can use the OnBehalfOfUserCredential to get user info from the token.
