### ISSUE TITLE
Adding External Items as an Entity type in Custom Copilot Sample for Microsoft 365

### ISSUE THREAD

**Issue by muwagerikpe** [OfficeDev/teams-toolkit#11561]
**Is your feature request related to a problem? Please describe.**
The current custom copilot template for Microsoft 365 data does not include externalItem as an entity type in the Graph Search API for RAG. Connected content is a significant part of the story for GPT authoring in Teams Toolkit and Copilot Studio, so we should ensure we keep that consistent story for custom copilots.

**Describe the solution you'd like**
Add externalItem as an entity type in the Graph Search API call in the custom copilot template for Microsoft 365 data.

**Describe alternatives you've considered**
The supported entity types could be included in the ReadMe of the template.

**Additional context**
N/A

**Comment by MuyangAmigo** [comment]
@muwagerikpe Thanks for raising it, this has been added to our backlog.

**Comment by MuyangAmigo** [comment]
Being worked on as part of this PR: https://github.com/OfficeDev/teams-toolkit/pull/11953
