### ISSUE TITLE
Error with code.ui required error: failed to get access token cache silently, please login first: you need login first before get access token. IOS Device

### ISSUE THREAD

**Issue by DayanK** [OfficeDev/teams-toolkit#11602]
**Describe the bug**
I receive an error message when I try to connect with the Graph API to get the user profile.

The error message I receive is:
"Error with code.ui required error: failed to get access token cache silently, please login first: you need login first before getting access token on iOS mobile devices."

The Teams application works perfectly on Android.

Here is the code I use for authentication. Could you please tell me how to fix this bug?

export async function GetGraphEntity(options : string[], api : string, query : string, filter : string) {

  const { scope } = { scope : ["User.Read"], ...options } ;

  const credential : TeamsFx = new TeamsFx(IdentityType.User, {
    initiateLoginEndpoint : process.env.REACT_APP_START_LOGIN_PAGE_URL !,
    clientId : process.env.REACT_APP_CLIENT_ID !
  }) ;

  try {
    credential.setSsoToken((await credential.getCredential().getToken(["User.Read Calendars.ReadWrite Contacts.Read MailboxSettings.ReadWrite"])) !.token ) ;
  } catch (err : unknown) {
    if (err instanceof ErrorWithCode && err.code ?.includes(ErrorCode.UiRequiredError)) {
      await credential.login([
        "User.Read Calendars.ReadWrite Contacts.Read MailboxSettings.ReadWrite",
      ]) ;
      await credential.getCredential() ;
    }
  }
  const graph = createMicrosoftGraphClient(credential, [
    "User.Read Calendars.ReadWrite Contacts.Read MailboxSettings.ReadWrite",
  ]) ;

  const profile = await graph.api("/me").get() ;
  console.log("profile", profile)
}

"dependencies": {
  "@azure/msal-browser": "^2.22.1",
  "@azure/msal-react": "^1.3.1",
  "@fluentui/react": "^8.63.1",
  "@fluentui/react-northstar": "^0.66.3",
  "@microsoft/microsoft-graph-client": "^3.0.5",
  "@microsoft/teams-js": "^2.13.0",
  "@microsoft/teamsfx": "^2.2.1",
  "@microsoft/teamsfx-react": "^3.0.0",
  "@types/microsoft-graph": "latest",
  "msteams-react-base-component": "^3.1.0",
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
  "react-router-dom": "5.1.2",
  "react-scripts": "^5.0.1",
}

Script for auth-start.html and auth-end.html

 <script src="https://res.cdn.office.net/teams-js/2.0.0/js/MicrosoftTeams.min.js"
        integrity="sha384-QtTBFeFlfRDZBfwHJHYQp7MdLJ2C3sfAEB1Qpy+YblvjavBye+q87TELpTnvlXw4"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://alcdn.msauth.net/browser/2.21.0/js/msal-browser.min.js"
        integrity="sha384-s/NxjjAgw1QgpDhOlVjTceLl4axrp5nqpUbCPOEQy1PqbFit9On6uw2XmEF1eq0s" crossorigin="anonymous">
    </script>

<body>
    <script src="https://res.cdn.office.net/teams-js/2.0.0/js/MicrosoftTeams.min.js"
        integrity="sha384-QtTBFeFlfRDZBfwHJHYQp7MdLJ2C3sfAEB1Qpy+YblvjavBye+q87TELpTnvlXw4"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://alcdn.msauth.net/browser/2.21.0/js/msal-browser.min.js"
        integrity="sha384-s/NxjjAgw1QgpDhOlVjTceLl4axrp5nqpUbCPOEQy1PqbFit9On6uw2XmEF1eq0s" crossorigin="anonymous">
    </script>
    <script type="text/javascript">
        microsoftTeams.app.initialize().then(() => {
            // Get the tab context, and use the information to navigate to Azure AD login page
            microsoftTeams.app.getContext().then(async (context) => {
                // Generate random state string and store it, so we can verify it in the callback
                var currentURL = new URL(window.location);
                var clientId = currentURL.searchParams.get("clientId");
                var scope = currentURL.searchParams.get("scope");
                var loginHint = currentURL.searchParams.get("loginHint");

                const msalConfig = {
                    auth: {
                        clientId: clientId,
                        authority: `https://login.microsoftonline.com/${context.user.tenant.id}`,
                        navigateToLoginRequestUrl: false
                    },
                    cache: {
                        cacheLocation: "sessionStorage",
                    },
                };

                const msalInstance = new msal.PublicClientApplication(msalConfig);
                const scopesArray = scope.split(" ");
                const scopesRequest = {
                    scopes: scopesArray,
                    redirectUri: window.location.origin + `/auth-end.html?clientId=${clientId}`,
                    loginHint: loginHint
                };
                await msalInstance.loginRedirect(scopesRequest);
            });
        });
    </script>
</body>

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS:  iOS
 - Version 17.4.1

**CLI Information (please complete the following information):**

**Additional context**

**Comment by KennethBWSong** [comment]
@DayanK Thank you for using Teams Toolkit. This is known issue that Auth Code Flow is not fully supported on Outlook IOS. Would you please try to use OBO flow? You can refer to this [sample](https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/hello-world-tab-with-backend).
