### ISSUE TITLE
bug report: office-addin.UnhandledError

### ISSUE THREAD

**Issue by kharidukranthi** [OfficeDev/teams-toolkit#11605]
An unexpected error has occurred while performing the unknown task. {"stack":"TypeError: code.startsWith is not a function\n    at Object.assembleError (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:1101737)\n    at Function.doScaffolding (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:719021)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Function.generate (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:714884)\n    at Function.<anonymous> (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:800620)\n    at Coordinator.create (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:258253)\n    at Coordinator.<anonymous> (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:800620)\n    at Coordinator.<anonymous> (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:969193)\n    at FxCore.createProject (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:893676)\n    at FxCore.<anonymous> (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:804599)\n    at FxCore.exports.ErrorHandlerMW (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:973442)\n    at FxCore.<anonymous> (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:969193)","message":"code.startsWith is not a function"}

stack:
UnhandledError: An unexpected error has occurred while performing the unknown task. {"stack":"TypeError: code.startsWith is not a function\n    at Object.assembleError (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:1101737)\n    at Function.doScaffolding (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:719021)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Function.generate (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:714884)\n    at Function.<anonymous> (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:800620)\n    at Coordinator.create (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:258253)\n    at Coordinator.<anonymous> (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:800620)\n    at Coordinator.<anonymous> (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:969193)\n    at FxCore.createProject (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:893676)\n    at FxCore.<anonymous> (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:804599)\n    at FxCore.exports.ErrorHandlerMW (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:973442)\n    at FxCore.<anonymous> (c:\\Users\\USER\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.7.2024041607\\out\\src\\extension.js:2:969193)","message":"code.startsWith is not a function"}
    at Object.assembleError (<REDACTED: user-file-path>/extension.js:2:1101785)
    at Function.<anonymous> (<REDACTED: user-file-path>/extension.js:2:801110)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Coordinator.create (<REDACTED: user-file-path>/extension.js:2:258253)
    at Coordinator.<anonymous> (<REDACTED: user-file-path>/extension.js:2:800620)
    at Coordinator.<anonymous> (<REDACTED: user-file-path>/extension.js:2:969193)
    at FxCore.createProject (<REDACTED: user-file-path>/extension.js:2:893676)
    at FxCore.<anonymous> (<REDACTED: user-file-path>/extension.js:2:804599)
    at FxCore.exports.ErrorHandlerMW (<REDACTED: user-file-path>/extension.js:2:973442)
    at FxCore.<anonymous> (<REDACTED: user-file-path>/extension.js:2:969193)

**Comment by jayzhang** [comment]
@kharidukranthi Thanks for reporting, could you try next version of TTK: 5.8.0, which will be published soon.
