### ISSUE TITLE
Incomplete documentation for custom parameter for user in test tool 

### ISSUE THREAD

**Issue by IAM5K** [OfficeDev/teams-toolkit#11652]
**Describe the bug**
I have to give a customised user details to trigger installation activity. When we follow the current documentation it throws error that user parameter is not available.

- [Test Tool Sample App](https://github.com/OfficeDev/TeamsFx-Samples/tree/v3/test-tool-sample-app)
- [Customize Teams context](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/debug-your-Teams-app-test-tool.md#customize-teams-context)
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/6e743575-8c38-4344-9234-35ffc55bb459)

**To Reproduce**
1. Go to the .teamsapptesttool.yml file in the project's root folder.
2. Go to the users section and update the name, userPrincipleName, and email of the required user.
3. Run the test tool
4. See error and on vs code it will give pop-up to [seek help at](https://github.com/OfficeDev/TeamsFx/wiki/Available-actions-in-Teams-Toolkit#invalidlifecycleerror)

**Expected behavior**
A tested complete documentation should be available. 
**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/ab63154b-ce02-4900-914d-d1b7ffd6d9d0)
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/ed67f2c2-755b-494e-8a09-a7c26b8eb0a7)

**VS Code Extension Information (please complete the following information):**
- Teams Toolkit v5.8.0
- Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
- Date: 2024-05-07T05:16:23.416Z
- Electron: 28.2.8
- ElectronBuildId: 27744544
- Chromium: 120.0.6099.291
- Node.js: 18.18.2
- V8: 12.0.267.19-electron.0
- OS: Linux x64 6.5.0-13parrot1-amd64

**CLI Information (please complete the following information):**

**Additional context**

**Comment by qinezh** [comment]
@IAM5K You need to create a new file named `.teamsapptesttool.yml` under the project root. `teamsapp.testtool.yml` is Teams app yaml file. These two files serve for different purpose.

You may refer to [test-tool-sample-app](https://github.com/OfficeDev/TeamsFx-Samples/blob/dev/test-tool-sample-app/.teamsapptesttool.yml) for reference.

**Comment by IAM5K** [comment]
I have tried this,
Even on updating the users list and current user i am getting the default user details on installation.
The user i expect to get is not available.

**Comment by IAM5K** [comment]
That was a great help,It worked
Here are my findings:
- If anyone want to get your id on the installation then add it in place of `current user`
- Live changes on `.teamsapptesttool.yml` doesn't work, same as env files and that is a normal behavior.

Thanks @qinezh 
I have raised a doubt about linting in bot framework, it would be amazing if you can please help me on that as well.
#11674
