### ISSUE TITLE
bug report: Cannot create new app `command 'fx-extension.create' not found`

### ISSUE THREAD

**Issue by francovp** [OfficeDev/teams-toolkit#11679]
**Describe the bug**
Got error `command 'fx-extension.create' not found` when trying to create a new app thought Command Palette option "Teams: Create new app" 

Also, The side panel buttons cannot be clickable, not sure is for the same bug.

**To Reproduce**
1. Open Command Palette
2. Click on 'Teams: Create new app'
3. See error

**Expected behavior**
Should create new app

**Screenshots**
![image](https://github.com/OfficeDev/teams-toolkit/assets/2883350/e9de2d14-ca8e-40a9-a953-d8efe2bb521c)

![image](https://github.com/OfficeDev/teams-toolkit/assets/2883350/2f78273a-2e62-4540-83ed-24b3ee1ac0b4)

**VS Code Extension Information (please complete the following information):**
 - OS: macOS 14.2.1 (23C71)
 - Version v5.8.0

**Additional context**

Version 5.6.0 works just fine.

**Comment by tecton** [comment]
Hi @francovp, based on your description and screenshots, the Teams Toolkit extension is not activated as expected. If you still have this bug after restarting VS Code, could you please share the error logs in console for us to analyze? (Click "Help" -> "Toggle Developer Tools" and you will see the console)

**Comment by karol-traczyk** [comment]
Hi, I have the same issue. In the console I can see
```
mainThreadExtensionService.ts:113 Activating extension 'TeamsDevApp.ms-teams-vscode-extension' failed: vscode.LanguageModelChatSystemMessage is not a constructor.
$onExtensionActivationError @ mainThreadExtensionService.ts:113
```

**Comment by tecton** [comment]
@karol-traczyk Thanks for the information.

We will fix this bug as soon as possible.
As a workaround, you could update VS Code to the latest version (>=1.88.1).

**Comment by tecton** [comment]
Teams Toolkit 5.8.1 has fixed this issue.
