### ISSUE TITLE
Custom App Upload

### ISSUE THREAD

**Issue by HimanshuPadhiyar** [OfficeDev/teams-toolkit#11726]
Type: <b>Bug</b>

I am trying to creating teams app from teams toolkit from visual studio however custom app upload error is showing everytime when I add teams sample app, I had enable the upload custom app from teams admin center a week ago but same error displaying everytime.
 

Extension version: 5.8.0
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|19.80GB (3.61GB free)|
|Process Argv|--crash-reporter-id 050561c2-3d7b-4b53-908c-131e86832474|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31049070
a69g1124:31058053
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by tecton** [comment]
Hi @HimanshuPadhiyar, could you please paste the error message or screenshot of "custom app upload error"?

**Comment by alexbbell** [comment]
I have a similar problem.
I created a HelloWorld app - Tab with SPFX and React. When I try add an app to Teams, I got the error. 

I found that the error is from ..... /_api/web/hostedapps/add
{
    "error": {
        "code": "-1, Microsoft.SharePoint.Client.ResourceNotFoundException",
        "message": "Cannot find resource for the request SP.RequestContext.current/web/hostedapps/."
    }
}

I am not the admin of the tenant. Can it be connected with it?

**Comment by tecton** [comment]
@alexbbell We'll check the error. If you are using local debug (F5) to add the Tab app with SPFx, admin permission is not required. It's used when you generate a SharePoint package and deploy it to tenant App Catalog.

**Comment by alexbbell** [comment]
thank you in advance. I hope you will find how to fix the error. 

I could execute an app as local debug. but now I have other problems.
If my SPFX works with SharePoint data (lists) and I use 'web' from 'context', 
must these lists be located in the root tenant site or I can store them in another site collection?

**Comment by HuihuiWu-Microsoft** [comment]
> thank you in advance. I hope you will find how to fix the error.
> 
> I could execute an app as local debug. but now I have other problems. If my SPFX works with SharePoint data (lists) and I use 'web' from 'context', must these lists be located in the root tenant site or I can store them in another site collection?

Hi @alexbbell, the lists don't need to be in the root tenant site, you can store them in other sites. Just make sure to update the site url where you SharePoint lists are located.
