### ISSUE TITLE
FindMember become slower when stored conversations number increase

### ISSUE THREAD

**Issue by tbaggio** [OfficeDev/teams-toolkit#11743]
Hello !

**Describe the bug**
On the **TeamsFX NodeJS SDK** (latest), the `findMember` method has become very slow since I have more than 100 persisted conversations in my storage.
When I first put my **Teams Bot** into production, sending proactive notifications to a Teams user took about 7 seconds (With less conversations stored ~10), now it's 2 minutes.

**To Reproduce**
1. Send any adaptive card to my endpoint (**See code below**)
2. The request is being processed
3. `findMember` list every conversations on the bucket, get them and try to get member informations from an MS API.
4. While getting member informations, I see some errors spawning. some users may have blocked the conversation with the bot (**See Screenshot below**)
5. The user receive the notification, 2min after the request started to be processed

**Expected behavior**
The time to send a notification is way too long.

**Screenshots**
<img width="1112" alt="Capture d’écran 2024-05-30 à 10 02 25" src="https://github.com/OfficeDev/teams-toolkit/assets/54032166/1e108e7e-3ad0-4f0c-b781-5c0a40eb6a6c">

**Additional context**
The bot only send notifications to my users.
To find the right user, I use the `findMember` method available on `BotBuilderCloudAdapter.ConversationBot` class.
The condition used for matching is `member.account.email === email`.
1:1 conversations are stored in an S3 compatible bucket.

Here is the bot declaration : 

```ts
export const notificationApp = new ConversationBot({
  adapterConfig: {
    MicrosoftAppId: config.botId,
    MicrosoftAppPassword: config.botPassword,
    MicrosoftAppType: "MultiTenant",
  },
  notification: {
    enabled: true,
    store: new S3ConversationReferenceStore(s3, config.s3BucketName),
  },
});
```

And the endpoint code:

```ts
type Payload = {
  email: string;
  card: AdaptiveCards.Schema;
}

server.post(
  "/api/notification",
  restify.plugins.queryParser(),
  restify.plugins.bodyParser(),
  async (req, res) => {
    const { email, card }: Payload = req.body;

    const member = await notificationApp?.notification?.findMember(async (m) => m.account.email === email)

    if (!member) {
      console.log(`Could not find member with email ${email}`);
      return res.json({
        code: 404,
      });
    }

    await member.sendAdaptiveCard(card, async (err) => {
      console.log(`error while sending adaptive card to ${email}`, err);
    });

    res.json({
      code: 200,
    });
  }
);
```

**Comment by qinezh** [comment]
If the notifications are sent only to personal chat (1:1 conversation), you may set search scope to personal chat while calling `findMember`. It helps reduce the calls of listing all members from group or channel conversations. 

The code would be like:

```typescript
const member = await notificationApp?.notification?.findMember(
  async (m) => m.account.email === email, 
  BotBuilderCloudAdapter.SearchScope.Person
)
```

**Comment by qinezh** [comment]
> I've already come across this solution but it's no good. I only have 1:1 conversations with users. How to speed up the process if I have only 1 type of conversation ?
 
For your scenario, as you already customized the conversation reference store, you may consider inserting new property like `userEmail` into the conversation reference item while adding it, then add a method to query conversation reference with the new property.
 
then the code would be like:
```
const conversationReference = S3ConversationReferenceStore.findConversationReferenceByUserEmail("foo@bar.com");
const target = notificationApp.notification.buildTeamsBotInstallation(conversationReferece);
await target.sendAdaptiveCard(card);
```
