### ISSUE TITLE
Cannot create new Teams apps with Teams Toolkit in Visual Studio Community 17.10.2

### ISSUE THREAD

**Issue by adr15** [OfficeDev/teams-toolkit#11834]
When trying to create a new Teams app using Teams Toolkit in Visual Studio, I'm always getting a message "The system cannot find the path specified. (Exception from HRESULT: 0x80070003)". The project is created but incomplete.

I've encountered this issue after updating the last version of VS (17.10.2) - but not sure this is the issue.
I've reinstalled VS and the operating system, the behavior is the same.

I've installed same VS Community 17.10.2 with Microsoft Teams development tools options from scratch on a new computer - the same behavior.

Until some weeks ago I've used Teams Toolkit with no issues.

In VS log the full record is:

  <entry>
    <record>3081</record>
    <time>2024/06/15 20:43:19.971</time>
    <type>Error</type>
    <source>Template provider aggregator</source>
    <description>System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESULT: 0x80070003)&#x000D;&#x000A;   at Microsoft.VisualStudio.CommonIDE.Solutions.Interop.IVsNativeEnvironmentInternal.WizLoadAndRunFile(String pwszWizard, String pwszDestination, Boolean bCloseSolution, Boolean bRunSilent, Array psaCustomParams, String pwszFrameworkVersion)&#x000D;&#x000A;   at Microsoft.VisualStudio.CommonIDE.Solutions.Dte.DteSolution.&lt;AddFromTemplateExAsync&gt;d__248.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.CommonIDE.Solutions.Dte.DteSolution.&lt;AddFromTemplateExAsync&gt;d__248.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.CommonIDE.Solutions.Dte.DteSolution.&lt;AddFromTemplateExAsync&gt;d__248.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()&#x000D;&#x000A;   at Microsoft.VisualStudio.CommonIDE.Solutions.Dte.DteSolution.AddFromTemplateEx(String FileName, String Destination, String ProjectName, String SolutionName, Boolean Exclusive, UInt32 Options)&#x000D;&#x000A;   at Microsoft.VisualStudio.CommonIDE.Solutions.Dte.DteSolution.&lt;&gt;c__DisplayClass25_0.&lt;EnvDTE100.Solution4.AddFromTemplateEx&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.NewProjectDialog.LegacyVsTemplateProvider.GetInstantiationResult(CreateProjectResult result)&#x000D;&#x000A;   at Microsoft.VisualStudio.NewProjectDialog.LegacyProjectTemplateProvider.&lt;InstantiateTemplateAsync&gt;d__10.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.TemplateProviders.TemplateProviderSupport.ExceptionLoggingTemplateProviderDecorator.&lt;InstantiateTemplateAsync&gt;d__9.MoveNext()</description>
  </entry>
  <entry>
    <record>3082</record>
    <time>2024/06/15 20:43:20.172</time>
    <type>Error</type>
    <source>SccDisplayInformation.SolutionOptions</source>
    <description>Unable to load solution user option &apos;SccProvider.Solution.LoadCount&apos;</description>
  </entry>
  <entry>
    <record>3083</record>
    <time>2024/06/15 20:43:20.176</time>
    <type>Error</type>
    <source>SccDisplayInformation.SolutionOptions</source>
    <description>Unable to load solution user option &apos;SccProvider.Solution.LastBranch&apos;</description>
  </entry>

**Comment by Alive-Fish** [comment]
Hi @adr15, thanks for reporting. Could you provide more information about the following questions?
1. Do you try to create other templates, such as a console app?
2. What template of Teams do you try to create?
3. Can you run the commands on the older project?

**Comment by adr15** [comment]
> Hi @adr15, thanks for reporting. Could you provide more information about the following questions?
> 
> 1. Do you try to create other templates, such as a console app?
> 2. What template of Teams do you try to create?
> 3. Can you run the commands on the older project?

1 - any other template works, except the ones created with Teams Toolkit
2- Echo and AI ChatBot
3 - Yes, if I open old projects they work with no problems

**Comment by Alive-Fish** [comment]
Thanks. Can you check if there is a folder `Microsoft.TeamsFx.Sdk` under `%VS_Installer_Path%/MSBuild/Sdks` and there are some files under `Microsoft.TeamsFx.Sdk/Sdk`? Seem like:

![image](https://github.com/OfficeDev/teams-toolkit/assets/15262146/761d4e12-5d01-4aab-acb0-6c2fa0c82fd3)

By the way, where do you find the VS logs? I want to reproduce your issue.

**Comment by adr15** [comment]
> Thank you. Can you check if there is a folder `Microsoft.TeamsFx.Sdk` under `%VS_Installer_Path%/MSBuild/Sdks` and there are some files under `Microsoft.TeamsFx.Sdk/Sdk`? Seem like:
> 
> ![image](https://private-user-images.githubusercontent.com/15262146/340515059-761d4e12-5d01-4aab-acb0-6c2fa0c82fd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODE1MDQsIm5iZiI6MTcxODc4MTIwNCwicGF0aCI6Ii8xNTI2MjE0Ni8zNDA1MTUwNTktNzYxZDRlMTItNWQwMS00YWFiLWFjYjAtNmMyZmEwYzgyZmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3MTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NTdmNGJmNmNkNTVlYmRjNjM5Y2ZjZjY0MDA2YTMxYTVkN2MzYWE4ODllMDU5M2ExNTI0NzMyMGMwNmIxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BNKdt_sOljMQ0l3oc_OYTxD92agZMkSA3gogIV6wHyw)
> 
> By the way, where do you find the VS logs? I hope to reproduce the issue and see the log.

Yes, I have the folder and and the files.

I'll try later to generate another log file and get back with location deleted the other file and don't remember were it was

**Comment by Alive-Fish** [comment]
That's strange. I am not sure why it happened on your machine, but there is an environment that can control the template content. You can try to set system environment `TEAMSFX_NEW_PROJECT_TYPE` to `false` and try to create a new Teams App project again. Remember you need close the Visual Studio installer and Visual Studio instance after changing the environment.

Hope it can help you. Thanks!

**Comment by davidclinger** [comment]
I had the same error message resulting in an incompletely created new project working in 17.10.3. I was able to work around it by running VS as administrator.

**Comment by Alive-Fish** [comment]
Thank you @davidclinger.

**Comment by adr15** [comment]
After updating Visual Studio to last version 17.0.4 the problems seems solved - I don't have this behavior anymore. I think the problem was related to Visual Studio, not to Teams Toolkit.
Thank you for support and prompt replies !

**Comment by thisispaulsmith** [comment]
> That's strange. I am not sure why it happened on your machine, but there is an environment that can control the template content. You can try to set system environment `TEAMSFX_NEW_PROJECT_TYPE` to `false` and try to create a new Teams App project again. Remember you need close the Visual Studio installer and Visual Studio instance after changing the environment.
> 
> Hope it can help you. Thanks!

I've had this same issue. Restarting as admin didn't fix it. However setting the environment variable did the trick.

**Comment by thisispaulsmith** [comment]
Noticed that setting the environment variables to true results in the error occuring. False results in the older project structure but no error.

However, noticed that I had "create .sln in the same folder" which seems to be the cause of the error. Disabling this, the errors went away.
