### ISSUE TITLE
Teams tab app error - CP.UiRequiredError: Failed to get access token cache silently, please login first: you need login first before get access token.

### ISSUE THREAD

**Issue by umalhotra86** [OfficeDev/teams-toolkit#11876]
**Describe the bug**
Teams tab application is failing to load. This error is observed in console - Uncaught (in promise) CP.UiRequiredError: Failed to get access token cache silently, please login first: you need login first before get access token.

**To Reproduce**
1. Deploy the teams react application to azure. Manifest is attached.
2. Launch application in desktop/web.
3. UI fails to load due to the error described above.

**Expected behavior**
Access token will be retireved and API calls to web API's hosted on azure will succeed.

**Screenshots**
![image](https://github.com/OfficeDev/teams-toolkit/assets/44616592/ffc40121-68b7-4d05-82fa-ba7368881317)

**OS**
 - OS: Windows 10

**Node version/ Script references**
 - Node version: 18.20.3
 - msal-browser script reference in auth-start & auth-end.html: https://alcdn.msauth.net/browser/2.21.0/js/msal-browser.min.js
[manifest.qa.json](https://github.com/user-attachments/files/15927856/manifest.qa.json)
[manifest.stage.json](https://github.com/user-attachments/files/15927857/manifest.stage.json)
[package.json](https://github.com/user-attachments/files/15927865/package.json)

**Comment by KennethBWSong** [comment]
Hi @umalhotra86 Thank you for using Teams Toolkit. UiRequiredError is expected when user have not consented permission for the app. When getting this error, you need to popup login page for user to consent using the following lines:
```
await teamsUserCredential!.login(["YOUR_PERMISSION"]);
```

**Comment by umalhotra86** [comment]
@KennethBWSong Already taking care of this in the logic. Before requesting for token, we ensure that login call has succeded. Shared below the function that ensures this.

`public validateToken = async (scopes: any) => {
    try {
      await teamsUserCredential?.getToken(scopes);
    } catch (error) {
      await teamsUserCredential?.login(scopes);
    }
  };
`

**Comment by blackchoey** [comment]
@umalhotra86 As synced in another thread, please use lower version @microsoft/teamsfx to workaround this issue.
