### ISSUE TITLE
Reload caché in Microsoft Teams Tab

### ISSUE THREAD

**Issue by Hector-Mina-98** [OfficeDev/teams-toolkit#11913]
**Describe the bug**
In MS Teams for Windows I am trying to refresh my Tab (which loads an html page). From the server I am sending the following headers:
```
Cache-Control: no-cache, no-store, must-revalidate
Expires: 0
Pragma: no-cache
```

But still, the page within the Teams Tab is not updated.
Currently the only possible way I have found is by deleting this directory:
`%appdata%/../Local/Packages/MSTeams_8wekyb3d8bbwe/LocalCache`

But it is a very complex solution for users.

Is there any other option to reload the cache? Any header, for example? Since that's how it should work.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/11181

**Comment by MuyangAmigo** [comment]
Close as copied over to https://github.com/MicrosoftDocs/msteams-docs/issues/11181
