### ISSUE TITLE
What is the purpose of creating an AAD application?

### ISSUE THREAD

**Issue by yunbozhang-msft** [OfficeDev/teams-toolkit#11925]
### Discussed in https://github.com/OfficeDev/teams-toolkit/discussions/11924

<div type='discussions-op-text'>

<sup>Originally posted by **yunbozhang-msft** June 29, 2024</sup>
Hi team,

Since ClientSecret cannot be used and the only way to authenticate is through certificates, I would like to know what is the use of creating an AAD App here? Can it be deleted? Because I found that we already have botAadApp.

![image](https://github.com/OfficeDev/teams-toolkit/assets/44389598/71a55790-01a0-4b76-8686-e286a4f8d5da)

Thanks!

</div>

**Comment by blackchoey** [comment]
@yunbozhang-msft In general, the app created by `aadApp/create` is used to acquire permission to call external APIs like Microsoft Graph API. And the app created by `botAadApp/create` is used to register a bot for your Teams app. The best practice is to use different AAD apps for the different purposes. So you can see the project creates 2 AAD apps. And you can't delete one of them if your bot app needs to call an external API protected by AAD.

Can you share which sample or template you're trying? I can share where are the 2 AAD apps used if you're interested in.

**Comment by yunbozhang-msft** [comment]
Hi @blackchoey thanks for your help.
I refer to this sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-proactive-messaging-teamsfx/teamsapp.yml#L13

Actually, I question is can I change to use certificate in aadApp/create? Instead of client secret. Thanks!

**Comment by blackchoey** [comment]
@yunbozhang-msft Seems the app does not call external APIs. You could try to delete the `aadApp/create` action and remove the reference of produced environment variables in other actions and try again.

For using certificate, you can absolutely use it to replace client secret in your code.
The `aadApp/create` action currently does not support cert related operation. Please obtain a cert from trusted CA by yourself and add it to related AAD app. If you think TTK should automate the steps, please open a feature request issue in this repo and I can follow up with that.

**Comment by blackchoey** [comment]
Created https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/1311 to update the sample. Please let us know if you have further questions.
