### ISSUE TITLE
Install manifest with setup.exe

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/teams-toolkit#11959]
I would like to try to create a setup.exe that allows you to install the add-in manifest directly into the client of the user running it, but I can't find anything on the internet or in the forums. I would like to know if there is some way to do it or if there is already some tool that allows you to do it. I know distribution is done through other processes but I would like to try a different approach if possible.

I noticed that using the command "npx @microsoft/teamsapp-cli install --xml-path manifest.xml" it is possible to install the add-in manifest in sideload mode, there is the possibility of doing so without the form appearing entering user credentials? Maybe taking them from somewhere?

I noticed that on some PCs it is not possible to start the local server which runs at the following path "http://localhost:53487" is there a possibility of doing it differently?

**Comment by jayzhang** [comment]
@CodeCube0 Thanks for feedback. Two questions to confirm your requirements: 
1. You need a way to install the add-in manifest in non-interactive mode that directly read user credentials from some place?    
2. What do you mean by doing it differently instead of running the local server for local sideloading? Do you mean sideload from a remote server deployed beforehand?

**Comment by CodeCube0** [comment]
Hello @jayzhang for your first question: Yes I would need to run the manifest.xml installation silently without user interaction. I would like to recover the Microsoft user logged into the Windows PC if possible so as not to disturb him during the installation.

for your second question: I noticed that when the credentials are requested to log in to the Microsoft account and retrieve the authentication token, a redirect is performed to a local server which "I think" is performed via nodejs. There wouldn't be a different way to do it

**Comment by jayzhang** [comment]
@CodeCube0  Thanks for clearify. Is it OK for you if: we provide a way to login without interaction. Prerequisite is you need to turn off the Multi Factor Authentications for your M365 account and set environment variables for your m365 credential (**M365_ACCOUNT_NAME**, **M365_ACCOUNT_PASSWORD**). Then you could sign in without UI flow by `**teamsapp auth login m365 -i false**`. We could enable this feature in the next release of TTK.

**Comment by CodeCube0** [comment]
Sure, that would be great. A thousand thanks @jayzhang

**Comment by jayzhang** [comment]
@CodeCube0 You can try this CLI version: https://www.npmjs.com/package/@microsoft/teamsapp-cli/v/3.0.3-beta.2024071606.0
