### ISSUE TITLE
Notifications - “Failed to decrypt conversation id” when sending activity

### ISSUE THREAD

**Issue by I566748** [OfficeDev/teams-toolkit#11988]
**Describe the bug**
We are facing issue while trying to decrypt conversation id when sending notifications from Bot. Below is the code to find the member using email to which notification has to be sent. 

const member = await commandApp.notification.findMember(
      async m => m.account.userPrincipalName.toLowerCase() === notificationData.email
    );

Currently it works only for 1 bot service while we have issues with remaining.

**Comment by qinezh** [comment]
@I566748 would you please provide the SDK version and the related error message?

**Comment by I566748** [comment]
Version details : "@microsoft/adaptivecards-tools": "^1.3.2",
    "@microsoft/teamsfx": "^2.3.2",
    "@six/concur-translator": "^1.0.9",
"botbuilder": "^4.22.0",
    "botframework-connector": "^4.22.0",

**Comment by I566748** [comment]
comments: request: {
    method: POST,
    url: https://smba.trafficmanager.net/apac/v3/conversations/.../activities/...
  },
  response: {
    body: '{"error":{"code":"BadArgument","message":"Failed to decrypt conversation id"}}',
    headers: HttpHeaders { _headersMap: [Object] },
    status: 403
  },
  body: {
    error: {
      code: 'BadArgument',
      message: 'Failed to decrypt conversation id'
    }
  }

**Comment by qinezh** [comment]
If the notification installation doesn't match the bot ID or password, you can get a **Failed to decrypt conversation ID** error. One possible cause for this error is that the bot ID or password is changed.
 
You can resolve this issue by cleaning your notification storage and reinstall your bot in Teams to ensure the new installation is up to date.
 
Each stored notification installation is bound with one bot. If you're able to check your notification storage, its bot field should match the bot you're running such as the bot ID with the same GUID.
