### ISSUE TITLE
supportsSingleSignOn removed from manifest when publishing

### ISSUE THREAD

**Issue by ksdaniel** [OfficeDev/teams-toolkit#11980]
**Describe the bug**

When importing app packages that have the microsoftEntraConfiguration node in the authorization section - the microsoftEntraConfiguration gets removed during import. 

This results in a validation error when we try to "preview" the application. 

**To Reproduce**

Create a teams message with the following parameters:

- message extension
- api based
- entra authentication

This will create a manifest file with the following node:

```
"authorization": {
                "authType": "microsoftEntra",
                "microsoftEntraConfiguration": {
                    "supportsSingleSignOn": true
                }
            }
```

Provision the resources for the application.

Import the application to Teams.

In the "imported" manifest the authorization node looks like this:

"authorization": {
"authType": "microsoftEntra"
},

When you try to preview the application you will get an validation message saying: Api based compose extension with microsoftEntra authType have no microsoftEntraConfiguration defined. Api based compose extension with microsoftEntra authType does not set supportsSingleSignOn to true

**Expected behavior**

After the application is deployed to teams we should see the authorization node in the manifest and the application should authenticate to the Azure Function using Entra.

**VS Code Extension Information (please complete the following information):**

Teams Toolkit v5.8.1
Microsoft Teams version 24152.415.2975.367.

**Comment by huimiu** [comment]
Hey @ksdaniel, thanks for reaching out. This is a known issue. The Teams Developer Platform doesn't currently support the Microsoft Entra for authentication.

But don't worry, you don't need to manually import your app into Teams. The Teams Toolkit will automatically sideload your app through a different method, not using the Teams Developer Platform. For instance, when you press F5 and the browser opens Teams, your message extension app should be there.

**Comment by huimiu** [comment]
Hey @ksdaniel, let us close this issue first, feel free to let us know if you have any further questions, thanks!
