### ISSUE TITLE
Allow Azure service principal to update MS Teams developer portal app

### ISSUE THREAD

**Issue by g-dx** [OfficeDev/teams-toolkit#11994]
**Is your feature request related to a problem? Please describe.**
I'd like to ensure the MS Teams Developer Portal application definition is always in-sync with the application manifest I have stored in my Git repository.

To do this I'd like to setup a CI/CD pipeline to call the following Teams Toolkit CLI command when someone modifies the `manifest.json` file.

```sh
npx @microsoft/teamsapp-cli update --env test
```

Right now this fails because the CLI attempts to open a browser window to login to an M365 account.

**Describe the solution you'd like**

I'd like the service principal I setup in Azure Active Directory to be sufficient to invoke the update CLI command. 

So the following commands should execute successfully in a CI/CD pipeline:

```sh
npx @microsoft/teamsapp-cli auth login azure --interactive false --service-principal true --username $CLIENT_ID --password $CLIENT_SECRET --tenant $ILDM_TENANT_ID
npx @microsoft/teamsapp-cli update --env test
```

**Describe alternatives you've considered**

There does not appear to be an alternative.

**Additional context**

**Comment by MuyangAmigo** [comment]
Hey @g-dx - This is a known issue and we have pushed a fix: https://github.com/OfficeDev/teams-toolkit/pull/11978

This will be included in next beta version of Teams Toolkit CLI, which will be released mid of next week.

**Comment by g-dx** [comment]
Hey @MuyangAmigo thanks for the response.

However, I had a look at the code in the linked pull request #11978 and it would seem to still require login to M365, just not interactively. My request was that an **Azure service principal** can update the MS Developer Portal app. 

Can you confirm whether this is possible or not?

**Comment by MuyangAmigo** [comment]
> Hey @MuyangAmigo thanks for the response.
> 
> However, I had a look at the code in the linked pull request #11978 and it would seem to still require login to M365, just not interactively. My request was that an **Azure service principal** can update the MS Developer Portal app.
> 
> Can you confirm whether this is possible or not?

For M365 account login, it's not possible to use Service Principal, but for Azure account, yes. M365 account supports using ID/Password to login with non-interactive mode.
