### ISSUE TITLE
API ME with Azure Functions fails after cloning solution from Github

### ISSUE THREAD

**Issue by BobGerman** [OfficeDev/teams-toolkit#11995]
**Describe the bug**
When I create a new API ME project, TTK correctly creates **local.settings.json**. This file is in gitignore, so when I try to run it from having cloned my project repo, this file is missing.
When I manually re-created the file everything started working.

**To Reproduce**
1. Create an API ME project with a new API within a git repository
2. Commit the project to github
3. In another folder or machine, clone the project from github
4. Project will not run; backend console will log this error:
[2024-07-10T19:02:54.779Z] The 'FUNCTIONS_WORKER_RUNTIME' setting is required. Please 
specify a valid value. See https://go.microsoft.com/fwlink/?linkid=2257963 for more information. The application will continue to run, but may throw an exception in a future release.
[2024-07-10T19:02:54.886Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your 
startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

Work-around is to manually re-create \local.settings.json with this content:

{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsFeatureFlags": "EnableWorkerIndexing"
  }
}

**Expected behavior**
Project should start after saving and cloning to github just the same as if it was a new project.

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 
 -  Version 10 or 11

**Additional context**
VS Code version 1.91.0 (user setup)
TTK version 5.8.1

**Comment by huimiu** [comment]
Hi @BobGerman, thanks for your feedback! I'll update our template to fix this issue.

**Comment by huimiu** [comment]
Hi @BobGerman, from my investigation, it seems like ignoring the `local.settings.json` file is a standard and safe practice. Many users tend to store keys in there, which can be risky if we commit it by default.

There's been [a similar issue](https://github.com/Azure/azure-functions-host/issues/8179) raised by developers in the Azure Functions repo, but Azure Functions still defaults to ignoring `local.settings.json`. They've expressed their concerns about it. Therefore, I think it makes sense for the Teams Toolkit template to follow this convention too. What do you think, @MuyangAmigo?

As for your workaround for the issue you're facing, maybe you could try manually removing `local.settings.json` from the .gitignore file and then commit it.
