### ISSUE TITLE
api bug 

### ISSUE THREAD

**Issue by Sibinagarjun** [OfficeDev/teams-toolkit#12002]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**

**Additional context**

**Comment by MuyangAmigo** [comment]
@Sibinagarjun Can you please share more details for the error?

**Comment by MuyangAmigo** [comment]
We will close the issue as there are no updates. Feel free to re-open with more details @Sibinagarjun
