### ISSUE TITLE
BotNotInConversationRoster for app with Message Extension via custom upload

### ISSUE THREAD

**Issue by jker-org** [OfficeDev/teams-toolkit#12038]
We are in the middle of submission process for our app. We are building an app that can be used in the compose area of a message (message extension). At first, the bot section in the manifest was filled:

![image](https://github.com/user-attachments/assets/71338756-5552-48a6-95a9-da9ce8202cdc)

This was working fine for message extension, but actually we don't want the users to chat with our bot (this was one feedback from submission). Therefore, we adapted the manifest and removed content from bot area:

![image](https://github.com/user-attachments/assets/398c4ce8-471c-4efa-b351-b6d3a5a3ca7c)

After adding the app to teams via custom upload, it will appear in the command list for the message:

![image](https://github.com/user-attachments/assets/7eb7d1f3-46e6-4131-a70b-c4dd996d118c)

The fetch task from the bot is also working fine. The dialog for user input is shown as expected:

![image](https://github.com/user-attachments/assets/ffae5368-a9fc-484f-98c9-754921a6a3f9)

Once we are done with getting the input, we submit the information to our bot. There we get the error message:

![image](https://github.com/user-attachments/assets/fc9068a9-5ab9-4fcc-965f-ecd7c37fc3bc)

The error message is misleading. From the fetch task and from former tests we know that our bot is working and can be reached. Our logs from the bot show the following error message:

**BotNotInConversationRoster**

We have build the message extension like in the samples from Teams Toolkit. Also this error does not make sense as the command was listed in the list of action for message extensions and also the fetch task was working.

Can you please check if this is a bug? Are we using the manifest wrong? We are happy to provide our manifest via personal message.

**This issue is currently blocking our app submission.**

Thanks!

**Comment by jker-org** [comment]
One more comment: The bot also tries to get the member context:
`await TeamsInfo.getMember(context, context.activity.from.id);`

Our assumption from documentation and examples is that this should work also with bot section empty in manifest.

**Comment by yukun-dong** [comment]
Hi @jker-org,

`TeamsInfo.getMember` is retrived as part of the bot context therefore it is mandatory to have bot in manifest.

**Comment by jker-org** [comment]
@yukun-dong : Thank you very much for your fast response. We have not been aware of this. We will think of a solution. Thanks!

**Comment by jker-org** [comment]
Hi @yukun-dong ! We have reworked our app. The bot section in manifest is empty. We still have the composeExtension filled.

We can upload the app via custom upload. We have a static page as well, so this is shown by default. When we go to any chat, we can successfully post an adaptive card via message extension.

**But:** We the user (that even has posted the adaptive card) want to hit the submit button, we get the following error in dev tools:

![image](https://github.com/user-attachments/assets/0919e0f1-df41-4fab-ab27-8b3515775f06)

```
{
    "errorCode": 0,
    "message": "Invoke validation failed. User forbidden to perform action",
    "standardizedError": {
        "errorCode": 209,
        "errorSubCode": 1,
        "errorDescription": "Invoke validation failed. User forbidden to perform action"
    }
}
```

That seems odd. What is the idea of message extension when the user can not interact with the adaptive card? With all actions, we use action.execute.

**Comment by jker-org** [comment]
@yukun-dong : I think I found the answer myself:

![image](https://github.com/user-attachments/assets/a6b1833a-071f-47bb-816f-ea73b1b34ee7)

https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1

So when the user wants to interact with the adaptive card, the BOT must be included in the bot sections of the manifest. Understood.
