### ISSUE TITLE
Getting ClientAuthError when trying to login to Microsoft 365

### ISSUE THREAD

**Issue by miktam** [OfficeDev/teams-toolkit#12030]
**Describe the bug**
Trying to log in to Microsoft 365, and after successful authentication in the browser, getting an error:

`{"errorCode":"network_error","errorMessage":"Network request failed","subError":"","name":"ClientAuthError","correlationId":"eac8f190-0c88-4a55-856a-f2d1ac75d828"}`

**To Reproduce**
1. Go to Teams Toolkit -> Accounts -> Microsoft 365
2. Click on Sign In
3. Login to Microsoft account

**Expected behavior**
It works fine when I'm using Github Codespace

**VS Code Extension Information (please complete the following information):**
 - OS: MacOS Sonoma 14.5
 - Version: Team Toolkit v5.8.1

**Additional context**

**Comment by miktam** [comment]
@xiaolang124 I am not using a proxy on my machine.

Thank you for the suggestion, I've run msal auth-node sample, and after running it, I'm getting 'OK' in the browser and successful logs in the console:

```
Msal Node Auth Code Sample app listening on port 3000!
Successfully acquired token using Authorization Code.
```

**Comment by miktam** [comment]
@xiaolang124 I've managed to make it work, using a new user on the same machine.
now can authenticate in m365 without any issues.
thank you for your support!

**Comment by gukoff** [comment]
I'm seeing the same error. Latest MacOS and extension.

This error message seems to be related to the m365 tooling in general:

- https://github.com/pnp/cli-microsoft365/issues/3533
- https://github.com/pnp/cli-microsoft365/issues/3533

It would be great to get a more informative error that suggests what's actually wrong.

---

Maybe helpful - I see this in the Developer tools when the error happens:

<img width="862" alt="image" src="https://github.com/user-attachments/assets/b2650ced-afd2-46e3-8826-c939aa4d08a2">

**Comment by mAbduqayum** [comment]
@gukoff did you manage to fix this issue?
