### ISSUE TITLE
Cannot see the option to create Copilot Plugin with the new teams toolkit extension for VSCode

### ISSUE THREAD

**Issue by zafarsyed** [OfficeDev/teams-toolkit#12066]
I'm trying to create an API Plugin package for Microsoft Copilot for Microsoft 365. I'm using Teams Toolkit extension in VSCode to do that. However, I cannot find the option **Copilot Plugin** under **Create a New App** option.

I'm using the Teams Toolkit extension version **v5.8.1**

![image](https://github.com/user-attachments/assets/88975cd3-5f45-44f7-a60a-be3fa6d2c8d5)

**Comment by SLdragon** [comment]
Hello, @zafarsyed , if you want to develop API plugin, you need to enable it in the Settings page as below:

File -> Preferences -> Settings -> Enable "Develop Copilot Plugin"

![image](https://github.com/user-attachments/assets/83c4db9b-0ac7-4dd5-94f3-2e7a1a60ffb8)

**Comment by zafarsyed** [comment]
@SLdragon I changed the settings and did reload the window, still don't see the option
![image](https://github.com/user-attachments/assets/9206bcec-277f-40ab-92ec-40d10efef3de)

**Comment by SLdragon** [comment]
Oh, for version 5.8.1, please also set the system environment variable API_COPILOT_PLUGIN to true and restart all VSCode instances for it to take effect. In future TTK releases, this environment variable will no longer be necessary

**Comment by zafarsyed** [comment]
@SLdragon thanks, it worked.
