### ISSUE TITLE
Adaptive Cards not shown on Mobile Teams App

### ISSUE THREAD

**Issue by jker-org** [OfficeDev/teams-toolkit#12064]
We are currently in the submission of a new app. Our app uses the bot framework and message extension features. The adaptive card is rendered inside the message of the user (message extension feature):

This works pretty fine in any Desktop client of Microsoft Teams:

![image](https://github.com/user-attachments/assets/0d22d28f-8fea-4258-bbde-166a1649608b)

However, when I open the same chat in the Mobile Version of Teams (Android + iOS), the adaptive card will be completely omitted.

![image](https://github.com/user-attachments/assets/7617231a-1ede-43d1-aa7a-c0a5480de3ff)

(See area bottom-left)

This issue is currently blocking the submission of our app. For this test, we used a simple adaptive card (2 labels). Can you confirm that this is a bug inside teams mobile apps?

**Comment by dooriya** [comment]
@jker-org I can view the card in Teams mobile (iPhone13 pro) for using the Message Extension sample from TTK.
I think this probably the bug in Teams mobile app.

![image](https://github.com/user-attachments/assets/24e95d16-c6fa-45b2-83e6-b816cefe8f8b)

**Comment by dooriya** [comment]
Close as issue has been copied over.
