### ISSUE TITLE
[Error] - code:AppStudioPlugin.TeamsAppUpdateFailed, 

### ISSUE THREAD

**Issue by prachibagade** [OfficeDev/teams-toolkit#12075]
[Error] - code:AppStudioPlugin.TeamsAppUpdateFailed, message: Unable to update Teams app with ID <<someid>> in Teams Developer Portal due to Unable to make API call to Developer Portal: AxiosError, Request failed with status code 422, API name: create-app, X-Correlation-ID: <<someid>>. This may be due to a temporary service error. Try again after a few minutes. data: "Error while updating assets to the blob storage for tenant id 5d5c9a50-c854-4ea3-b05d-16388b14d5b3, appDefinitionId <<someid>>. Error message: Error while deleting assets from the blob storage for tenant id <<someid>>, appDefinitionId <<someid>>. Error message: Key based authentication is not permitted on this storage account."

**Comment by atymic** [comment]
Same error here.

**Comment by rwenz02** [comment]
I have been getting the same error since yesterday.

**Comment by HuihuiWu-Microsoft** [comment]
Duplicated with https://github.com/OfficeDev/teams-toolkit/issues/12092

**Comment by leonardjohn** [comment]
same error here today.
