### ISSUE TITLE
Unable to create Teams app

### ISSUE THREAD

**Issue by suresh-at-straker** [OfficeDev/teams-toolkit#12089]
[AppStudioPlugin.TeamsAppCreateConflict]: Unable to create Teams app, which may be because your app ID is conflicting with another app's ID in your tenant. Click 'Get Help' to resolve this issue.

**********************************************************************************************

[Error] - Failed to Execute lifecycle provision due to failed action: teamsApp/create. TeamsAppCreateConflict:Unable to create Teams app, which may be because your app ID is conflicting with another app's ID in your tenant. Click 'Get Help' to resolve this issue.. Env output: {}
 [Info] - Execution summary:

Summary:
(×) Error: Lifecycle stage provision failed.
  (×) Error: teamsApp/create failed.
    (×) Error: Unable to create Teams app, which may be because your app ID is conflicting with another app's ID in your tenant. Click 'Get Help' to resolve this issue.
......
......

[Error] - code:AppStudioPlugin.TeamsAppCreateConflict, message: Unable to create Teams app, which may be because your app ID is conflicting with another app's ID in your tenant. Click 'Get Help' to resolve this issue.
 Help link: https://aka.ms/teamsfx-switch-account-or-subscription-help

**Comment by anishgurjar** [comment]
same issue

**Comment by HuihuiWu-Microsoft** [comment]
@suresh-at-straker Service has been recovered, please retry to see if the issue still exists.

**Comment by bdaunt457** [comment]
I had same issue. As of this morning, it's now working for me. No changes were made to the default project created from the "Microsift Teams Template" template. Visual Studio 2022 net 9.0

**Comment by HuihuiWu-Microsoft** [comment]
Root cause of this issue is the same with https://github.com/OfficeDev/teams-toolkit/issues/12092 and has been resolved.
