### ISSUE TITLE
[AppStudioPlugin.TeamsAppCreateConflict]: Unable to create Teams app, which may be because your app ID is conflicting with another app's ID in your tenant. Click 'Get Help' to resolve this issue.

### ISSUE THREAD

**Issue by anishgurjar** [OfficeDev/teams-toolkit#12081]
[AppStudioPlugin.TeamsAppCreateConflict]: Unable to create Teams app, which may be because your app ID is conflicting with another app's ID in your tenant. Click 'Get Help' to resolve this issue.

I'm not able to start a new teams app bot for some reason. It was working fine before, and created multiple bots before, but all of a sudden it's throwing this error. This is a new app, and there is no app ID conflicting (I checked the dev portal). 

Error occurs on Provision [1/6] step. Existing apps run correctly, it is only when I try to create a new app. I am signed into my M365 and have custom app upload, and I am using unique app name. 

Possible cause of error might be that I logged into another laptop with my credentials for M365 and Azure OpenAI (but this is unlikely why I'm getting the error)

**Comment by bdaunt457** [comment]
Same

**Comment by gjbundy** [comment]
I think this must be related to the other issue everyone is reporting. I decided to switch to provision to a new profile and started getting this error after I couldn't get the local one to provision.

**Comment by HuihuiWu-Microsoft** [comment]
Duplicated with https://github.com/OfficeDev/teams-toolkit/issues/12089
