### ISSUE TITLE
bot not answering when previewing through cli

### ISSUE THREAD

**Issue by Robstei** [OfficeDev/teams-toolkit#12117]
**Describe the bug**

**To Reproduce**
1. Follow the insturctions form this official microsoft tutorial: https://microsoftlearning.github.io/MS-4001-Build-collaborative-apps-for-Microsoft-Teams/Instructions/Labs/3-Guided-project/5-Exercise%204.html
2. preview app with the cli (npx teamsapp preview -b chrome in my case)
3. Debug session is started but the bot is not responsive

**Expected behavior**
The bot should be responsive. The bot is responsive when using this button from the VS Code extension
![image](https://github.com/user-attachments/assets/56aba530-c980-451f-9d55-5d362132129b)

**Screenshots**
Output when running npx teamsapp preview -b chrome:
![image](https://github.com/user-attachments/assets/177d20ca-87d2-484a-a338-57e889720c1b)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version: 10.0.226311
- teamsapp version: 3.0.2

**Comment by swatDong** [comment]
@Robstei - from your log there's a line "`Run Command: The log of this task can be found in C:\User...`"
Could you please check if there's any error or unexpected log in the log file?

In addition, in the popup browser window, is the Teams account the same as the one used in teamsapp CLI?
