### ISSUE TITLE
Team SharePoint Error/Issue :Error: TypeError: Cannot read properties of undefined (reading 'componentType') 

### ISSUE THREAD

**Issue by BrucedeMink** [OfficeDev/teams-toolkit#12128]
**Describe the bug**
We use a SharePoint list as our App Hub data source. App Hub is a graphically rendered set of important links for our organisation.
I believe its a Teams/Sharepoint Connection issue.

It quit working 5-6 weeks ago, and I am trying to debug and find a solution.
![image](https://github.com/user-attachments/assets/a6a824cd-6d61-455d-905f-8837a294d3dd)

**Errors from VS Code Debug Console**
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/data-resolvers-search-800d59a7d809cd04.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/data-resolvers-search-800d59a7d809cd04.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/sb-activated-d0f8998e2955846e.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/sb-activated-d0f8998e2955846e.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/563350-31a1680b4c112a85.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/563350-31a1680b4c112a85.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/sb-commanding-complete-f92999da0ed751c5.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/sb-commanding-complete-f92999da0ed751c5.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/365365-4117fee0b040bb6b.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/365365-4117fee0b040bb6b.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/105338-3a758c04cf35bab4.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/105338-3a758c04cf35bab4.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/105705-e45073c89d1973da.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/105705-e45073c89d1973da.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/746643-cc3710175239c505.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/746643-cc3710175239c505.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/960043-ea1fd5e9da773668.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/960043-ea1fd5e9da773668.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/699377-a254b64c820654c8.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/699377-a254b64c820654c8.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/736549-0c6bf6c1230f0cf2.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/736549-0c6bf6c1230f0cf2.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/867964-8fe94c2ffce175cd.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/867964-8fe94c2ffce175cd.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/services-search-930c6c747a1b518e.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/services-search-930c6c747a1b518e.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/299320-f718dc6e1dca9f9e.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/299320-f718dc6e1dca9f9e.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/58150-f5de52cf8e82a0d3.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/58150-f5de52cf8e82a0d3.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/72814-0bf6ff11d2348c80.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/72814-0bf6ff11d2348c80.js.map: undefined
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/search-app-d6692e415a9ccf16.js: Unexpected 403 response from https://local.teams.office.com/sourcemaps/hashed-assets/search-app-d6692e415a9ccf16.js.map: undefined

![image](https://github.com/user-attachments/assets/dd78d882-ea70-4ad9-804b-4561ba6e796d)

when I run through the dev tools I see a few errors which I am not sure how to resolve:
![image](https://github.com/user-attachments/assets/236b848a-ec0c-4bee-843a-72ab225ba584)

**Expected Resolution**
I want to publish the app back into the production environment without errors so our users can start to use it again. 

When I run it via local host the solution works this is what it is meant to look like:
![image](https://github.com/user-attachments/assets/73c44de3-4e47-47fa-94f5-9f28af7bfd5e)

I am thinking more and more that this is an SSO issue or Authentication issue

**Comment by BrucedeMink** [comment]
![image](https://github.com/user-attachments/assets/2ba39781-310e-49d5-8274-34afb0b092db)
Further Errors I have seen from Teams Side

**Comment by ungsdev** [comment]
I’ve encountered a similar error before.

If it’s an SPFx-based Tab app, check if the related SharePoint App has been removed or disabled from the Tenant App Catalog.

If it is there correctly, check it is installed on all sites or at least in the top-level site collection.

I hope this helps.

**Comment by HuihuiWu-Microsoft** [comment]
Hi @BrucedeMink , the SPFx web part wasn't available in SharePoint Online as you showed to me in our last live troubleshooting meeting. So I believe this is not an issue of Teams/SharePoint Auth. It should be something wrong with the deployment itself instead. You could raise an GitHub issue to SPFx team first for further suggestions.
BTW, could you help check whether there're any errors when you build and deploy the SPFx project?

**Comment by HuihuiWu-Microsoft** [comment]
As we discussed and connected in another thread, this issue has been resolved. To those who may encounter the same issue, this issue proved to be caused by some configuration settings and the web part was not available in the SharePoint App Center which caused a disconnect between Teams and SharePoint.
