### ISSUE TITLE
Newly created webpart not visible in teams App..

### ISSUE THREAD

**Issue by devanihiren** [OfficeDev/teams-toolkit#12130]
I am creating webpart using below command

yo @microsoft/sharepoint --skip-install true --component-type webpart --component-name <WEBPART NAME> spo --skip-feature-deployment true --is-domain-isolated false

webpart created successfull.
Now added tab to the manifest.json file with the newly created webpart id.
Using below command to build project :

 gulp clean 
 gulp bundle --ship
 gulp package-solution --ship
 
 Then manually uploading new .sppkg to the App catalog and override existing .sppkg
 Now i can not see newly created Tab to the Team App.
 Also same webpart visible in Sharepoint Site.
 How to Fix this issue?how to manually upload with new Tabs in Teams

**Comment by HuihuiWu-Microsoft** [comment]
Hi @devanihiren, thanks for reporting issue to us. You could try our Teams Toolkit VS Code extension to create a SPFx project where you don't need to manually configure Teams manifest file.

**Comment by HuihuiWu-Microsoft** [comment]
Hi @devanihiren, do you still have the issue with Teams Toolkit? Any updates?

**Comment by devanihiren** [comment]
Solved ..Without Teams Toolkit

**Comment by HuihuiWu-Microsoft** [comment]
@devanihiren Glad to hear that, but still I strongly suggest you to try Teams Toolkit where you can focus on your app and Teams Toolkit will handle other things for you. 
I'll close this issue as it has been solved.

**Comment by devanihiren** [comment]
Yes , Right , But i am working in AWS Workspace where i  am not able to login in Teams Toolkit. That's why i am managing manually.
Here is the Issue : https://github.com/OfficeDev/teams-toolkit/issues/11976
Thanks
