### ISSUE TITLE
MS Teams Toolkit Error

### ISSUE THREAD

**Issue by MoonAlzoubi26z** [OfficeDev/teams-toolkit#12131]
I'm starting new on the Teams Toolkit i followed the steps on the toolkit plugin page and i'm getting an error in this step:
Run Local Preview.
and this is the output:
[Error] - Failed to Execute lifecycle provision due to failed action: teamsApp/validateManifest. ManifestValidationFailed:Manifest Validation is unsuccessful! Unable to get schema from https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json, message: Failed to get manifest at url https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json due to: request to https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json failed, reason: connect ETIMEDOUT 23.33.241.144:443. Env output: {"TEAMS_APP_ID":"74028ab9-f369-42ff-ab93-57a1a0e008fb","TEAMS_APP_TENANT_ID":"59f4d0e9-1e36-4c52-94c1-84176ffa43e5","TAB_DOMAIN":"localhost:53000","TAB_ENDPOINT":"https://localhost:53000"}
[2024-07-31T16:16:31.655Z] [Info] - Execution summary:

Summary:
(×) Error: Lifecycle stage provision failed.
  (√) Done: teamsApp/create was executed successfully.
    (√) Done: Teams app with id 74028ab9-f369-42ff-ab93-57a1a0e008fb already exists, skipped creating a new Teams app.
  (√) Done: script was executed successfully.
    (√) Done: Successfully executed command echo "::set-teamsfx-env TAB_DOMAIN=localhost:53000"; echo "::set-teamsfx-env TAB_ENDPOINT=https://localhost:53000";
  (×) Error: teamsApp/validateManifest failed.
    (×) Error: Manifest Validation is unsuccessful! Unable to get schema from https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json, message: Failed to get manifest at url https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json due to: request to https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json failed, reason: connect ETIMEDOUT 23.33.241.144:443
  (!) Warning: teamsApp/zipAppPackage was not executed.
  (!) Warning: teamsApp/validateAppPackage was not executed.
  (!) Warning: teamsApp/update was not executed.
  (!) Warning: teamsApp/extendToM365 was not executed.
![Teams](https://github.com/user-attachments/assets/7dee2975-1d57-4ad7-b95b-766adc73edfb)

**Comment by anchenyi** [comment]
hi @MoonAlzoubi26z , the reason is that your network cannot access the json schema. Could you check if you can open this link ( https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json) in your browser?

**Comment by MoonAlzoubi26z** [comment]
Thank you anchenyi, this is what i see when i open the schema json:

![Github](https://github.com/user-attachments/assets/81c3f96f-8636-45d4-a9e5-3c2c29c09aab)

I see the JSON schema.

**Comment by anchenyi** [comment]
hi @MoonAlzoubi26z , it looks like you do have access to this json schema. Could you retry in the Teams Toolkit? It might be due to a network spike before.

**Comment by MoonAlzoubi26z** [comment]
I restarted the VS Code and i ran the debug again, the error happens at this step:
(2/3) Action cli/runNpmCommand(install dependencies): running npm command.
npm ERR! errno ETIMEDOUT

![Teams](https://github.com/user-attachments/assets/83132c4b-42e7-4068-9746-b3aeb66b2bb6)

**Comment by anchenyi** [comment]
hi @MoonAlzoubi26z, for further investigation, could you tell me which template your are using or share your project codes?

**Comment by MoonAlzoubi26z** [comment]
I'm using Basic Tab, i haven't added any code just followed the steps from the plug-in start page.
![image](https://github.com/user-attachments/assets/b6bdb630-e402-4cab-9437-32e1c827dc44)

![image](https://github.com/user-attachments/assets/9bba3eb3-c123-4a9e-85ff-55a97bb22775)

![image](https://github.com/user-attachments/assets/30a9f7e9-421e-4227-9899-414327e85e4f)

This is my first app with the teams toolkit and i wanted to deploy a hello world app or any other app just to see if it works.
Let me know please if you need more info or if you have any suggestions

**Comment by Siglud** [comment]
> I restarted the VS Code and i ran the debug again, the error happens at this step: (2/3) Action cli/runNpmCommand(install dependencies): running npm command. npm ERR! errno ETIMEDOUT
> 
> ![Teams](https://private-user-images.githubusercontent.com/177035822/355558164-83132c4b-42e7-4068-9746-b3aeb66b2bb6.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTM3MDcsIm5iZiI6MTcyMzA5MzQwNywicGF0aCI6Ii8xNzcwMzU4MjIvMzU1NTU4MTY0LTgzMTMyYzRiLTQyZTctNDA2OC05NzQ2LWIzYWViNjZiMmJiNi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwNTAzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTAxMWRlOWNjOTUyNjVkZTdmNjgyZDgwNDM0NjlmYzZlNDc2MDU4M2VmYTU5YTczMDExNmQ0OWFiNjhhNDhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2iXaQqA0NWxMqttJ7oOlQa1GdTc1U-Azr55ZJMehR6w)

it looks like your `npm install` command running failed. 
Please try to run `npm install` command in your project root folder and paste the console output of this command. Thanks

**Comment by MoonAlzoubi26z** [comment]
It turned out the company's VPN is causing this issue, i was able to debug and run without any issues after a disconnected the vpn.

Thank you all
