### ISSUE TITLE
Getting error while using graph api in team meeting tab

### ISSUE THREAD

**Issue by srivatsabs** [OfficeDev/teams-toolkit#12149]
I am getting below error when i try to use this Microsoft Teams Meeting Tab(helloWorld In-meeting app sample)
"Uncaught TypeError TypeError: _microsoft_microsoft_graph_client_authProviders_azureTokenCredentials__WEBPACK_IMPORTED_MODULE_4__.TeamsUserCredential is not a constructor"

this is my code 
import React from "react";
import { app, teamsCore } from "@microsoft/teams-js";
import MediaQuery from "react-responsive";
import "./App.css";
import { AppCredentialAuthConfig, AppCredential } from "@microsoft/teamsfx";
import { Client } from "@microsoft/microsoft-graph-client";
import { TokenCredentialAuthenticationProvider,TeamsUserCredential  } from "@microsoft/microsoft-graph-client/authProviders/azureTokenCredentials";

const authConfig = {
  clientId: 'f0fc2917-1c77-4b30-b3df-7b6e68ec6123',
  initiateLoginEndpoint: 'https://login.microsoftonline.com/',
};

class Tab extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      context: {},
    };
  }

  componentDidMount() {
    app.initialize().then(() => {
      app.notifySuccess();

      app.getContext().then(async (context) => {
        this.setState({
          meetingId: context.meeting.id,
          userName: context.user.userPrincipalName,
        });
        const meetingId = context.chat.id;
        const teamsUserCredential = new TeamsUserCredential(authConfig);
        const authProvider = new TokenCredentialAuthenticationProvider(teamsUserCredential, {
          scopes: ["Chat.ReadBasic"],
        });
        
        const graphClient = Client.initWithMiddleware({ authProvider: authProvider });
        const profile = await graphClient.api("/me").get();
        try {
        const response = await graphClient
          .api(`/chats/${meetingId}`)
          .version('beta')
          .get();
        console.log("Graph API response:", response);
      } catch (error) {
        console.error("Error calling Graph API:", error);
      }
        if (context.page.frameContext === "sidePanel") {
          teamsCore.registerOnLoadHandler((context) => {
            // Use context.contentUrl to route to the correct page.
            app.notifySuccess();
          });

          teamsCore.registerBeforeUnloadHandler((readyToUnload) => {
            // Dispose resources here if necessary.
            // Notify readiness by invoking readyToUnload.
            readyToUnload();
            return true;
          });
        }
      });
    });
  }

  render() {
    let meetingId = this.state.meetingId ?? "";
    let userPrincipleName = this.state.userName ?? "";

    return (
      <div>
        <h1>In-meeting app sample</h1>
        <h3>Principle Name:</h3>
        <p>{userPrincipleName}</p>
        <h3>Meeting ID:</h3>
        <p>{meetingId}</p>
        <MediaQuery maxWidth={280}>
          <h3>This is the side panel</h3>
          <a href="https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-apps-in-meetings">
            Need more info, open this document in new tab or window.
          </a>
        </MediaQuery>
      </div>
    );
  }
}

export default Tab;

**Comment by JerryYangKai** [comment]
Hi @srivatsabs!
The error you're encountering is because the TeamsUserCredential is not being imported correctly. To resolve the issue, you may need to update your import statement for TeamsUserCredential.

Replace the following line:

import { TokenCredentialAuthenticationProvider,TeamsUserCredential  } from "@microsoft/microsoft-graph-client/authProviders/azureTokenCredentials";  
 
with:

import { TokenCredentialAuthenticationProvider } from "@microsoft/microsoft-graph-client/authProviders/azureTokenCredentials";  
import { TeamsUserCredential } from "@microsoft/teamsfx";

**Comment by srivatsabs** [comment]
Get SSO token failed with error: App resource defined in manifest and iframe origin do not match, I am getting this error now, do we have any working sample where I can start learning from it.

**Comment by JerryYangKai** [comment]
You can refer to this template:
https://github.com/OfficeDev/teams-toolkit/tree/dev/templates/ts/sso-tab-with-obo-flow
