### ISSUE TITLE
Unable to Create New App: Tab with SPFx

### ISSUE THREAD

**Issue by ungsdev** [OfficeDev/teams-toolkit#12143]
**Describe the bug**
When trying to create a new SPFx-based tab app, the following error occurs.

```
[2024-08-02T02:45:35.743Z] [Info] - yo@latest not found, installing...
[2024-08-02T02:45:35.743Z] [Info] - Start installing...
[2024-08-02T02:45:35.745Z] [Error] - Failed to execute npm install yo@latest
[2024-08-02T02:45:35.746Z] [Error] - Failed to install yo@latest, error = 'NpmInstallFailed: Unable to run 'npm install' due to spawn EINVAL'
[2024-08-02T02:45:35.749Z] [Error] - code:SPFx.LatestPackageInstallFailed, message: Unable to set up SPFx environment in HOME/.fx folder. To set up global SPFx environment, follow [Set up your SharePoint Framework development environment | Microsoft Learn](https://aka.ms/teamsfx-spfx-dev-environment-setup).
```

![image](https://github.com/user-attachments/assets/f64697ed-4e40-4f2c-a864-bcb4d2dce662)

My SPFx environment is set up correctly according to the documentation provided in the error message. In fact, I have been working well with it until recently.

Here are the Node version and the list of globally installed Node modules in my environment.

```
PS C:\Users\ungsd> node -v
v18.20.4
PS C:\Users\ungsd> npm ls --global --depth=0
C:\Program Files\nodejs -> .\
├── @microsoft/generator-sharepoint@1.19.0
├── corepack@0.28.0
├── gulp-cli@3.0.0
├── npm@10.7.0
└── yo@5.0.0
```

![image](https://github.com/user-attachments/assets/ca1da757-7e62-4ae3-93f7-2970dce12ebc)

**To Reproduce**
1. Go to Visual Studio Code > Teams Toolkit Extension
2. Click on 'Create a New App'
3. Select 'Tab' option
4. Select 'SPFx' option
5. Select 'Create New SPFx Solution' option
6. Select 'Install the latest SPFx locally in Teams Toolkit directory' option
7. Proceed with the remaining steps
8. Check OUTPUT console to see error

**Expected behavior**
The new app should be created without any errors.

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11 / 23H2 / 22631.3737
 - Version: v5.8.1

**Additional context**
Additionally, the following error occurs when selecting the ‘Use globally installed SPFx’ option instead 'Install the latest SPFx locally in Teams Toolkit directory'.

```
[2024-08-02T02:57:02.728Z] [Error] - code:SPFx.DevEnvironmentSetupError, message: Your SPFx development environment is not set up correctly. Click "Get Help" to set up the right environment.
 Help link: https://aka.ms/teamsfx-spfx-dev-environment-setup
```

![image](https://github.com/user-attachments/assets/6b51cf42-7b87-4fd6-a911-6075c23b7e2d)

It seems there is an issue with finding the globally installed Node modules in the environment. This might be related to the issue below.

https://github.com/nodejs/node/issues/52554#issue-2245848776

**Comment by HuihuiWu-Microsoft** [comment]
@ungsdev Thanks for reporting this issue to us. We're working on it and will update to you soon.

**Comment by HuihuiWu-Microsoft** [comment]
@ungsdev The fix has been merged and please expect that in our next prerelease. I'll close this one first and feel free to reopen if it doesn't work with next build.

**Comment by ungsdev** [comment]
To someone who needs an immediate alternative: You can create a new SPFx-based tab app using the teamsapp CLI.

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-cli?pivots=version-three

```
PS C:\Users\ungsd> npm install -g @microsoft/teamsapp-cli^C
PS C:\Users\ungsd> npm ls --global --depth=0
C:\Program Files\nodejs -> .\
├── @microsoft/generator-sharepoint@1.19.0
├── @microsoft/generator-sharepoint@1.19.0
├── @microsoft/teamsapp-cli@3.0.2
├── corepack@0.28.0
├── gulp-cli@3.0.0
├── npm@10.7.0
└── yo@5.0.0

PS C:\Users\ungsd> teamsapp new
Some arguments/options are useless because the interactive mode is opened. If you want to run the command non-interactively, add '--interactive false' after your command.
? New Project Tab
? App Features Using a Tab SPFx
? SharePoint Solution Create New SPFx Solution
? SharePoint Framework Use globally installed SPFx
? Framework React
? Name for SharePoint Framework Web Part mySPFxWP
? Directory where the project folder will be created in (./) 
? Directory where the project folder will be created in ./
? Application Name tabwithspfx
████████████████████  100% | [4/4] Scaffolding project  (√) Done.
████████████████████  100% | [1/1] Create  (√) Done.
Project created at: C:\Users\ungsd\tabwithspfx
PS C:\Users\ungsd>
```
![image](https://github.com/user-attachments/assets/44cbd204-fd08-44c9-a4e8-9985b21af8dd)

**Comment by React365-Chris** [comment]
what if you are adding a new SPFX web part as a tab in an existing teams toolkit project that has other spfx tabs?

**Comment by HuihuiWu-Microsoft** [comment]
@React365-Chris You could try `teamsapp add` with teamsapp CLI. See [teamsapp CLI manual guide](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-cli?pivots=version-three#teamsapp-add)  for more details

**Comment by React365-Chris** [comment]
I tried that first. I use the CLI more than VSCode. I have the same error, which is unfixable.

**Comment by HuihuiWu-Microsoft** [comment]
@React365-Chris Yes, I just checked and that's because TTK will first detect globally installed SPFx version which will cause failure due to https://github.com/nodejs/node/issues/52554#issue-2245848776 while `teamsapp create` doesn't if user manually choose `use globally installed SPFx`. Please expect our next build which will ship soon.
