### ISSUE TITLE
Typo in whatsnext.svg

### ISSUE THREAD

**Issue by hanjiankang** [OfficeDev/teams-toolkit#12165]
A typo exist in the sentence "_Project specific documenation_"

**To Reproduce**
1. Go to TeamsToolkit extension in VS Code
2. Click on Get Started button
3. Click on What's next?
4. Typo loads on the right-side under the README.md header

**Expected behavior**
The correct word is "_documentation_"

**Screenshots**
![image](https://github.com/user-attachments/assets/f865f735-a43a-4c1b-9e2b-8a6f7e5652ed)

**VS Code Extension Information (please complete the following information):**
 - Version 5.8.1

**Comment by tecton** [comment]
@hanjiankang Thank you, I've fixed it.
