### ISSUE TITLE
OnAfterRenderAsync does not fire in configurable tabs.

### ISSUE THREAD

**Issue by mmsharepoint** [OfficeDev/teams-toolkit#12186]
**Describe the bug**
protected override async Task OnAfterRenderAsync does not fire in configurable tabs.

**To Reproduce**
1. Set up a default Tab project
2. Only do default steps
4. Press F5
5. Add as personal app --> works
6. Add to a team --> doesn't work

**Expected behavior**
protected override async Task OnAfterRenderAsync should fire in configurable tabs as well

**VS Extension Information (please complete the following information):**
 - OS: Windows
 - Version 17.10.63.65054

**Comment by mmsharepoint** [comment]
It seems you missed to insert
@rendermode InteractiveServer
into the TabConfig.razor template

And this has another error:
Make sure that 
$"{NavigationManager.BaseUri}/tab"
doesn`t end up with a "...//tab" in the url as it fails to display in the tab

**Comment by huimiu** [comment]
Thanks @mmsharepoint, let me check our template and get back to you!

**Comment by huimiu** [comment]
Hey @mmsharepoint, sorry for late reply, could you please upgrade to VS 17.11 and give it a try? We've updated the templates in the new version of the Teams Toolkit, mainly migrating configurable tabs to static tabs. You can read more about it in [this doc](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-channel-group-tab?tabs=vs&pivots=node-java-script#migrate-your-configurable-tab-to-static-tab).

I tried it with VS 17.11.2 and was able to successfully add the tab to Teams. If you run into any issues with the new version, please let us know. Thanks!
