### ISSUE TITLE
Unable to configure the bot in the Microsoft Teams

### ISSUE THREAD

**Issue by tbhaxor** [OfficeDev/teams-toolkit#12200]
**Describe the bug**

I am novice in the MS teams and bot development. I have created the project from the basic bot template and added the configure properties as guided [here](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bot-configuration-experience?tabs=JS1%2Cteams-bot-sdk2%2Cteams-bot-sdk3#update-app-manifest). 

```json
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json",
    "manifestVersion": "1.16",
    "version": "1.0.0",
    "id": "${{TEAMS_APP_ID}}",
    "developer": {
        "name": "Teams App, Inc.",
        "websiteUrl": "https://www.example.com",
        "privacyUrl": "https://www.example.com/privacy",
        "termsOfUseUrl": "https://www.example.com/termofuse"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "MyProject${{APP_NAME_SUFFIX}}",
        "full": "full name for MyProject"
    },
    "description": {
        "short": "short description for MyProject",
        "full": "full description for MyProject"
    },
    "accentColor": "#FFFFFF",
    "bots": [
        {
            "botId": "${{BOT_ID}}",
            "scopes": [
                "team",
                "groupchat"
            ],
            "supportsFiles": false,
            "isNotificationOnly": false,
            "configuration": {
                "groupChat": {
                    "fetchTask": true
                },
                "team": {
                    "fetchTask": true
                }
            },
        }
    ],
    "composeExtensions": [],
    "configurableTabs": [],
    "staticTabs": [],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": []
}
```

When I try to run the project from the teams toolkit, it fails at `teamsApp/validateManifest` step

```
Summary:
1 failed.
You can check and update your Teams manifest at ./appPackage/manifest.json.
(×) Error: /bots/0 must NOT have additional properties
```

And this is because of `configuration` key. When I checked the JSON schema, there is no such key available in the object of bots array, but the schema in the [documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#botsconfiguration) mentions otherwise.

**To Reproduce**
1. Create a new project with bot template
2. Follow documentation https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bot-configuration-experience?tabs=JS1%2Cteams-bot-sdk2%2Cteams-bot-sdk3#update-app-manifest

**VS Code Extension Information (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Version [e.g. 22] v5.8.1

**CLI Information (please complete the following information):**
 - OS: [e.g. iOS8.1] Linux 
 - Version [e.g. 22]3.0.2

**Additional context**

**Comment by anchenyi** [comment]
hi @tbhaxor, the doc you mentioned is outdated, and "Bots.configuration" is not supported now. I have reported this issue to the related PM team days ago, and I will get back to you ASAP. Sorry for the inconvenience.

**Comment by anchenyi** [comment]
hi @tbhaxor, you can try using the Adaptive Card. It allows you to configure the response template of user submissions, so that you can hide all sentitive data. You can refer to this sample project([link](https://github.com/OfficeDev/teams-toolkit-samples/tree/eb387adc56c79bc5bc41aef5c8bb4ad24ec85cb3/test-tool-sample-app)) and select the Adaptive Card you need.

Let me use one Adaptive Card from this project as an example to help you understand quickly. 
- `src/commands/reportIncidentCommandHandler.ts` is a registered command to handle user message: "report incident".
- `src/adpativeCards/reportIncidentResponse.json` is the report template.
- `src/adaptiveCards/incidentReportedResponse.json` is the response template of user submissions, you can edit this file to hide sensitive data.

**Comment by tbhaxor** [comment]
Is there anyway I could send the message to a particular user in the group/channel? Like in slack

**Comment by anchenyi** [comment]
hi @tbhaxor, for better future reference, could you open a separate GitHub issue to discuss how a group bot can send a message to a specific user? This issue will be used to continue tracking the updates to the bots.configuration section in the manifest. Thank you!

**Comment by tbhaxor** [comment]
Adaptive cards approach works for me.
