### ISSUE TITLE
Adaptive Card: Input.ChoiceSet: Selection jumps back to default value after action.execute

### ISSUE THREAD

**Issue by jker-org** [OfficeDev/teams-toolkit#12217]
**Describe the bug**
We have just published a new app to Microsoft Teams store. The app utilizes message extension feature and a bot from teams toolkit example. You can reproduce the issue with our app: https://tinyurl.com/teams-issue-example-app . The link will expire automatically on 31th August 2024. Please do not share any screenshots of our app due to privacy. Thanks!

An adaptive card with Input.ChoiceSet element and a (preselected) value is shown to the user. The user selects another value and performs the action.execute element.

The correct value (new) value is provided to the bot, but the wrong (old, preselected value) is shown again to the user. Even though the correct value is provided to the bot, this issue can cause a lot of confusion to the user and should be corrected.

**To Reproduce**
1. Create an adaptive card with input.choiceset and default value (e.g. with our app):

![image](https://github.com/user-attachments/assets/3cf01630-8230-44d0-97a9-c286a4f5dc4d)

2. Select another value:

![image](https://github.com/user-attachments/assets/016fb664-0ffd-41a9-8942-158d912a60f6)

3. Hit Submit

![image](https://github.com/user-attachments/assets/abb215bf-3686-45e7-9220-cb3825eb7bd2)

Although the correct (new) value is provided to the bot, the UI will show the old value for a brief moment.

**Expected behavior**

Please provide the new value to the bot and also keep the new value selected in the UI while the action.execute is processed. 

**CLI Information (please complete the following information):**
 - Teams Web (Edge)
 - Teams Desktop (Windows 10)

**Comment by dooriya** [comment]
@jker-org The `Action.Execute` can return an updated adaptive card as response to replace the current one. So if you want to keep the user's choice set selection in the chat, you can send an updated card with user's selection as the response to the card action. You can refer to [this document](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/work-with-universal-actions-for-adaptive-cards#adaptivecardaction-invoke-activity) for more details.

**Comment by jker-org** [comment]
@dooriya : Thank you for the example! In our app, we will return a different card where the user does not see the choices anymore.

The user will ask himself: What did the app report? Red or Blue? 

In our opinion, this is a bug. However, you can also treat it as feature request. The current behavior is very confusing to the user.

**Comment by dooriya** [comment]
@jker-orgI understand your issue now. You mean the user’s selection briefly appears in the chat window before the app returns the updated card. In my example, the default choice “Red” is shown for a brief moment while the button is grayed out.

This UI behavior is controlled by the Teams Client, copied this upstream issue to https://github.com/MicrosoftDocs/msteams-docs/issues/11482.

**Comment by jker-org** [comment]
@dooriya : Yes. Thank you! :-)

**Comment by dooriya** [comment]
Close here and track in the upstream issue.
