### ISSUE TITLE
Preview of adaptive card not shown in compose area

### ISSUE THREAD

**Issue by jker-org** [OfficeDev/teams-toolkit#12216]
**Describe the bug**
We have just published a new app to Microsoft Teams store. The app utilizes message extension feature and a bot from teams toolkit example. You can reproduce the issue with our app: https://tinyurl.com/teams-issue-example-app . The link will expire automatically on 31th August 2024. Please do not share any screenshots of our app due to privacy. Thanks!

After SubmitTask, our bot returns an adaptive card to be shown in the compose area:

```typescript
const attachment: MessagingExtensionAttachment = {
          contentType: attachment_content.contentType,
          content: attachment_content.content,
          preview: attachment_preview
        };

  const response: MessagingExtensionActionResponse = {
    composeExtension: {
      type: 'result',
      attachmentLayout: "list",
      attachments: [
        attachment
      ]
    }
  };

return response;
``` 
        

As you can see from developer tools, the invoke call is correctly replying the attachment with normal content and preview content.

![image](https://github.com/user-attachments/assets/50668562-728e-4d1e-83ea-ca77a0f8ebff)

In our case, normal content has action.execute elements, the preview element does not have action.execute elements.

In the compose area, however, the adaptive card from normal content is shown (with action.execute elements). 

**To Reproduce**

1. Go to any chat and add an app with message extension capabilities (like ours).
2. Create an adaptive card for the compose area.
3. Compare the adaptive card in the compose area with invoke output from network area in dev tools.

**Expected behavior**

* The compose area shows the preview content from invoke call (attachment.preview).
* When the adaptive card is posted to the chat, the actual content (attachment.content) from invoke call is written to chat.

**CLI Information (please complete the following information):**
 - Teams Web (Edge) 
 - Teams Desktop (Windows)

**Comment by dooriya** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/11475
Let's track in the upstream issue.

**Comment by dooriya** [comment]
Close here and check in the upstream issue.
