### ISSUE TITLE
Error on Preparing Teams App Dependencies

### ISSUE THREAD

**Issue by LALITAMITTAL18** [OfficeDev/teams-toolkit#12252]
I am creating new Teams Template project using Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.11.0
 and when I click on "Preparing Teams App Dependencies", I get below error:
{
  "errorType": "SystemError",
  "source": "Fx-VS",
  "name": "UnknownError",
  "message": "The given key was not present in the dictionary.",
  "stack": "   at System.ThrowHelper.ThrowKeyNotFoundException()\r\n   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at TeamsFx.VisualStudio.Commonlib.M365TokenProvider.<GetAccountInfoAsync>d__7.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at TeamsFx.VisualStudi...
  "innerError": null,
  "userData": null,
  "timestamp": "2024-08-20T14:56:23.0584746+02:00",
  "displayMessage": "The given key was not present in the dictionary.",
  "helpLink": null,
  "issueLink": null
}

![image](https://github.com/user-attachments/assets/38537e4e-f6ca-422f-9609-743727633888)

**Comment by lijie-lee** [comment]
Hi @LALITAMITTAL18, 

I'll help to track this issue and figure out why the Error occurs. By the way, could you share which Teams Template you created?

**Comment by LALITAMITTAL18** [comment]
I am trying Echo Bot

![image](https://github.com/user-attachments/assets/7b5ed2b2-0465-4943-a649-c38333a235c6)

**Comment by lijie-lee** [comment]
Got it. I'll have a try for this template. Thanks.

**Comment by lijie-lee** [comment]
Hi @LALITAMITTAL18,

It seems your [UPN](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/plan-connect-userprincipalname) is not configured. To verify this, you could try:
1. Retrieve **UPN** locally by following this [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/auth-code)
2. Go to the [Microsoft Admin Center](https://admin.microsoft.com/) to check if necessary configration is set.

**The best solution we recommended is to register a `M365 test account` and use the new account to develop and test teams app locally.**

**Comment by lijie-lee** [comment]
Hi @LALITAMITTAL18,  does the solution work for you?

> Hi @LALITAMITTAL18,
> 
> It seems your [UPN](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/plan-connect-userprincipalname) is not configured. To verify this, you could try:
> 
> 1. Retrieve **UPN** locally by following this [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/auth-code)
> 2. Go to the [Microsoft Admin Center](https://admin.microsoft.com/) to check if necessary configration is set.
> 
> **The best solution we recommended is to register a `M365 test account` and use the new account to develop and test teams app locally.**

**Comment by LALITAMITTAL18** [comment]
Yes it worked. There was some issue with logged in user. I have to sign out and sign in again using embedded browser.

![image](https://github.com/user-attachments/assets/ded81c52-42a0-4918-b471-819c0273e1d6)
