### ISSUE TITLE
bug report: unknown.UnhandledError

### ISSUE THREAD

**Issue by kammasheker** [OfficeDev/teams-toolkit#12310]
An unexpected error has occurred while performing the unknown task. {"stack":"Error: Timed out waiting for authentication provider to register\n\tat Object.assembleError (c:\\Users\\skamma\\.cursor\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.8.1\\out\\src\\extension.js:2:1178867)\n\tat exports.ErrorHandlerMW (c:\\Users\\skamma\\.cursor\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.8.1\\out\\src\\extension.js:2:1050250)\n\tat async FxCore.<anonymous> (c:\\Users\\skamma\\.cursor\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.8.1\\out\\src\\extension.js:2:1045956)","message":"Timed out waiting for authentication provider to register"}

stack:
UnhandledError: An unexpected error has occurred while performing the unknown task. {"stack":"Error: Timed out waiting for authentication provider to register\n\tat Object.assembleError (c:\\Users\\skamma\\.cursor\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.8.1\\out\\src\\extension.js:2:1178867)\n\tat exports.ErrorHandlerMW (c:\\Users\\skamma\\.cursor\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.8.1\\out\\src\\extension.js:2:1050250)\n\tat async FxCore.<anonymous> (c:\\Users\\skamma\\.cursor\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.8.1\\out\\src\\extension.js:2:1045956)","message":"Timed out waiting for authentication provider to register"}
	at Object.assembleError (<REDACTED: user-file-path>/extension.js:2:1178848)
	at exports.ErrorHandlerMW (<REDACTED: user-file-path>/extension.js:2:1050250)
	at async FxCore.<anonymous> (<REDACTED: user-file-path>/extension.js:2:1045956)

**Comment by HuihuiWu-Microsoft** [comment]
Hi @kammasheker Could you help check whether built-in 'Microsoft Account' extension is disabled on your side?
![image](https://github.com/user-attachments/assets/a02a8a4e-dd92-4b86-a533-320403b91de3)
