### ISSUE TITLE
teamsApp/publishAppPackage fails with BadRequest for some localizations

### ISSUE THREAD

**Issue by alexanderbob** [OfficeDev/teams-toolkit#12358]
**Describe the bug**
Running provisioning fails at the teamsApp/publishAppPackage stage with the following message:

`Error: Unable to make API call to Developer Portal: Error, BadRequest, API name: publish-app, X-Correlation-ID: cc2f521b-b7f7-4cf2-adf1-ad5612c92192. This may be due to a temporary service error. Try again after a few minutes. data: {"error":{"code":"BadRequest","message":"BadRequest","innerError":{"code":"BadRequest","date":"2024-09-09T20:42:30","request-id":"90d35443-509f-41d9-81b9-4c789f2aebec","client-request-id":"90d35443-509f-41d9-81b9-4c789f2aebec"}}}
`

```
{
  "errorType": "SystemError",
  "source": "Fx-VS",
  "name": "UnknownError",
  "message": "The JSON-RPC connection with the remote party was lost before the request could complete.",
  "stack": "   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__165.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n  ...
  "innerError": null,
  "userData": null,
  "timestamp": "2024-09-09T13:42:17.7659121-07:00",
  "displayMessage": "The JSON-RPC connection with the remote party was lost before the request could complete.",
  "helpLink": null,
  "issueLink": null
}
```

With trial and error, we narrowed this issue down to the length of localization properties.

For example, with manifest like the one below:

```
{
    "$schema": "https://developer.microsoft.com/json-schemas/teams/vDevPreview/MicrosoftTeams.schema.json",
    "manifestVersion": "devPreview",
    "version": "1.0.0",
    "id": "f12389cc-a4de-471e-a341-f413efc6f8cf",
    "packageName": "Microsoft.Dynamics.Sales.Productivity",
    "localizationInfo": {
        "defaultLanguageTag": "en-US",
        "additionalLanguages": [
            {
                "languageTag": "pl-PL",
                "file": "pl-PL.json"
            }
        ]
    },
    ...
}
```

And `pl-PL.json` file contents as the following:
```
{
    "$schema": "https://developer.microsoft.com/json-schemas/teams/vDevPreview/MicrosoftTeams.Localization.schema.json",
    "name.short": "Copilot dla działów sprzedaży",
    "name.full": "Copilot dla działów sprzedaży",
    "description.short": "Usługa...",
    "description.full": "...",
    ...
}
```

Provisioning fails with the error above.

Howver, shortening `name.short` string solves the issue:
```
{
    "$schema": "https://developer.microsoft.com/json-schemas/teams/vDevPreview/MicrosoftTeams.Localization.schema.json",
    "name.short": "dla działów sprzedaży",
    "name.full": "Copilot dla działów sprzedaży",
    "description.short": "Usługa...",
    "description.full": "...",
    ...
}
```

[Schema](https://developer.microsoft.com/json-schemas/teams/vDevPreview/MicrosoftTeams.Localization.schema.json) file declares that max length for `name.short` is 30 characters:
![image](https://github.com/user-attachments/assets/fade6f93-9678-44ec-aa0e-16fa450c2828)

However, all 3 strings for `name.short` property on lines 1-3 are causing provisioning to fail. Removing "Copilot" to shorten the string value (lines 6-8) solves the issue.
![image](https://github.com/user-attachments/assets/69550613-15a9-40b1-8613-b9b844d0e1b1)

1. Copilot dla działów sprzedaży
2. Copilot pārdošanas nodaļām
3. Copilot dành cho Bán hàng

Looks like API endpoint incorrectly counts length for multi-symbol unicode characters, because all 3 are no longer than 30 characters, but caret position is at 33/31 symbol.

Microsoft Visual Studio Enterprise 2022
Version 17.11.2
VisualStudio.17.Release/17.11.2+35222.181

**Comment by alexanderbob** [comment]
Looks like this error happens when localization file contains non-ascii characters in the required `name.short` property.

For example, with `manifest.json` file:
```
{
    "$schema": "https://developer.microsoft.com/json-schemas/teams/vDevPreview/MicrosoftTeams.schema.json",
    "manifestVersion": "devPreview",
    "version": "1.0.0",
    "id": "f12389cc-a4de-471e-a341-f413efc6f8cf",
    "packageName": "Microsoft.Dynamics.Sales.Productivity",
    "localizationInfo": {
        "defaultLanguageTag": "en-US",
        "additionalLanguages": [
            {
                "languageTag": "ar-SA",
                "file": "ar-SA.json"
            },
            ...
        ]
    }
    ...
}
```

and `ar-SA.json` containing:
```
{
    "$schema": "https://developer.microsoft.com/json-schemas/teams/vDevPreview/MicrosoftTeams.Localization.schema.json",
    "name.short": "للمبيعات",
    "name.full": "للمبيعات",
    "description.short": "يعيد ...",
    "description.full": "إن للمبي ...",
}
```

We are facing `BadRequest` error for both `update-published-app` and `publish-app` APIs.

However, replacing `name.short` with ASCII characters:
```
{
    "$schema": "https://developer.microsoft.com/json-schemas/teams/vDevPreview/MicrosoftTeams.Localization.schema.json",
    "name.short": "ASCII name",
    "name.full": "للمبيعات",
    "description.short": "يعيد ...",
    "description.full": "إن للمبي ...",
}
```

Solves the issue.

With this in mind, I am not sure if this is a Toolkit issue, or M365 API itself.

**Comment by XiaofuHuang** [comment]
@alexanderbob Thank you for reporting the issue. We are currently working on resolving it.

**Comment by anchenyi** [comment]
As discussed in Teams, the API endpoint correctly counts the characters. We will improve the error message for localization file's json schema validation.
