### ISSUE TITLE
Dependency Conflict for Custom Engine Copilot Templates with Teams AI Library

### ISSUE THREAD

**Issue by DakotaWray2** [OfficeDev/teams-toolkit#12375]
**Describe the bug**
A dependency conflict exists between teams-ai and openai versions in teams toolkit custom copilot templates preventing debug.
Debug fails at npm install.
Running npm install manually produces the screenshot below. 

**To Reproduce**
1. Create a New App > Custom Engine Copilot > Basic AI Chatbot > TypeScript > AOAI

**Screenshots**
![err](https://github.com/user-attachments/assets/0fd27a52-71c2-4070-b9e3-73ac7c0d973f)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11
 - Teams Toolkit: v5.9.2024081502 (pre-release)

**Comment by DakotaWray2** [comment]
I was able to get the templates to run by mirroring the versions of teams-ai and openai in the team-ai library's samples.

**Comment by kuojianlu** [comment]
@DakotaWray2 This is a known issue and has been fixed in the latest pre-release version. Yes, the change of openai and teams-ai version is the right solution.
