### ISSUE TITLE
Custom Copilot sample not working: ERESOLVE unable to resolve dependency tree 

### ISSUE THREAD

**Issue by therealjohn** [OfficeDev/teams-toolkit#12414]
Moved from https://github.com/microsoft/teams-ai/issues/2029.

---

Language
Javascript/Typescript

Version
latest

Description
npm i @microsoft/teams-ai
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: md@1.0.0
npm error Found: openai@4.28.5
npm error node_modules/openai
npm error openai@"~4.28.4" from the root project
npm error
npm error Could not resolve dependency:
npm error peer openai@"^4.61.0" from @microsoft/teams-ai@1.4.1
npm error node_modules/@microsoft/teams-ai
npm error @microsoft/teams-ai@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:

npm resolution error report
While resolving: md@1.0.0
Found: openai@4.28.5
node_modules/openai
openai@"~4.28.4" from the root project

Could not resolve dependency:
peer openai@"^4.61.0" from @microsoft/teams-ai@1.4.1
node_modules/@microsoft/teams-ai
@microsoft/teams-ai@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Reproduction Steps
npm i @microsoft/teams-ai

**Comment by therealjohn** [comment]
@sholtomaud,

You shouldn't need to `npm -i teams-ai` for this. After you create the project, try just pressing F5 / Start Debugging in VS Code. That should work as-is. 

My guess right now is that you are installing teams-ai to a newer version which has a bumped dependency package which is causing a conflict from the samples package.json settings.

**Comment by corinagum** [comment]
Sample customer is trying to run:
Custom CoPilot->AI Agent->TS->New Folder->SomeAppName->

**Comment by sholtomaud** [comment]
> @sholtomaud,
> 
> You shouldn't need to `npm -i teams-ai` for this. After you create the project, try just pressing F5 / Start Debugging in VS Code. That should work as-is.
> 
> My guess right now is that you are installing teams-ai to a newer version which has a bumped dependency package which is causing a conflict from the samples package.json settings.

I'm not doing anything other than following what you guys instructed and it's not working.

**Comment by kuojianlu** [comment]
@sholtomaud Please delete `openai` dependency from `package.json`, then run `npm install` again. This is a known issue and has been fixed in the lastest prerelease version of Teams Toolkit.

**Comment by sholtomaud** [comment]
Ok. Will do. 

But why would you market/advertise this when it's broken from the get go?

**Comment by kuojianlu** [comment]
> Ok. Will do.
> 
> But why would you market/advertise this when it's broken from the get go?

Will be fixed in the stable release ASAP.
