### ISSUE TITLE
Support for Dynamic Data Population in Adaptive Cards for Enhanced Workflows

### ISSUE THREAD

**Issue by sagarpinninti192** [OfficeDev/teams-toolkit#12413]
**Dear Microsoft Teams Development Team,**

I would like to propose a feature enhancement for Microsoft Teams that allows for the dynamic population of data in Adaptive Cards. This feature would be highly beneficial for creating task management workflows and other use cases where real-time data is required. Below are the specific details and requirements for this feature:

**Feature Request: Dynamic Data Population in Adaptive Cards**
We are working on a use case where Adaptive Cards are used to capture and submit task details within Microsoft Teams. To enhance this process, we propose adding the capability for dynamically fetching and displaying data within Adaptive Cards. This includes the ability to:

**Dynamically Populate User Data:**

**Description:** A dropdown (ChoiceSet) that lists all users currently participating in a Teams chat or group.
**Use Case:** The field would allow users to select individuals from the current chat/group for task assignments or other purposes.
**Dynamic Behavior:** This field should be able to automatically fetch and display all participants in the current chat or group at runtime.

**Dynamically Fetch and Display Related Data:**

**Description:** A dropdown (ChoiceSet) that lists data (e.g., assignment groups) based on the user selected in the first field.
**Use Case:** For task assignment, this field would dynamically query a backend system (e.g., ServiceNow) to fetch related data based on the selected user.
**Dynamic Behavior:** The field should automatically update to display the relevant options based on the user selection.

**Submit Action:**
Upon submission, the data from the Adaptive Card should trigger a backend process (e.g., creating a task in a third-party system such as ServiceNow), without posting the card to the Teams chat/group.
This interaction should occur seamlessly, using API calls or integrations with external systems, ensuring that workflows are automated and efficient.

**Justification & Benefits:**
**Improved User Experience:** Dynamically populating data in Adaptive Cards would streamline workflows, particularly in task management scenarios where real-time data is essential.
**Enhanced Automation:** This capability would reduce the need for manual inputs, minimizing errors and saving time.
**Seamless Integrations:** Supporting dynamic data in Adaptive Cards would improve the integration between Teams and external tools such as ServiceNow, Jira, and other task management systems, creating a more cohesive work environment.
This enhancement would significantly increase the flexibility of Adaptive Cards in Microsoft Teams, allowing for more powerful, real-time data-driven interactions.

**Thank you for your consideration. I look forward to any feedback or updates regarding this request.**

Best regards,
**Sagar Pinninti**
**Developer**

**Comment by MuyangAmigo** [comment]
Hey @sagarpinninti192, Thanks for your feature proposal! As this repository tracks issues for Teams Application Development, I will share your proposal to other teams in Microsoft. 

Also I would suggest you raise this via official Microsoft Feedback Portal for Teams: https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472?page=1&sort=most-votes, this way your feedback will be shared with the community and gets prioritized based on votes.

**Comment by MuyangAmigo** [comment]
Hey @sagarpinninti192 Closing this issue as there is no further actions needed from Teams Toolkit. Please let us know if you have additional comments.
