### ISSUE TITLE
Can't "Sign in to Azure" using a separate account

### ISSUE THREAD

**Issue by stokedout** [OfficeDev/teams-toolkit#12436]
**Describe the bug**

Nothing happens when I click "Sign in to Azure" in the extension panel. Or the button changes so that it's connected with the Microsoft 365 account signed in above it. There's also no option to sign out. I don't want to do this. I have a separate Microsoft 365 account from the Azure account therefore I need to log in to both independently. 

**To Reproduce**
1. Go to VS code 
2. Click on Teams Toolkit
3. Click Sign in to Microsoft 365 with user@16vdp5.onmicrosoft.com
4. Click Sign in to Azure - nothing happens unless I click the info circle at the side (later it shows the above account as the azure account)

**Expected behavior**
* Sign in to Azure with an account of my choice via Teams Toolkit extension
* Display a list of subscriptions under the signed in account to choose from via Teams Toolkit extension

**Screenshots**
<img width="419" alt="image" src="https://github.com/user-attachments/assets/b28d5250-29c8-4a48-bc95-1451d8e0d7e3">

**VS Code Extension Information (please complete the following information):**
 - OS: macOS Sonoma 14.4.1 (23E224)
 - Version v5.8.1

**CLI Information (please complete the following information):**
 - OS: n/a
 - Version n/a

**Additional context**

**Comment by stokedout** [comment]
> There's also no option to sign it

Edit: I meant sign out

**Comment by HuihuiWu-Microsoft** [comment]
Hi @stokedout 

- Could you help reload/restart VSC and see whether the issue persists?
- Azure 'sign out' has been moved to 'Accounts' sidebar at left bottom of VSC. You could check your signed in Azure account there and select to sign out.

**Comment by stokedout** [comment]
Thanks, I did what you suggested and it works. It's confusing that you can sign out of the Microsoft 365 account one way, and Azure another.

<img width="404" alt="image" src="https://github.com/user-attachments/assets/d889ad89-3c28-4088-8f8b-a53d099931ab">

**Comment by HuihuiWu-Microsoft** [comment]
Thanks @stokedout for your feedback. Azure sign out is moved to 'Accounts' sidebar since TTK is leveraging auth provided by VSC. I'll create an item to record your feedback and discuss with PM later.
