### ISSUE TITLE
When creating a Basic Tab and choosing TypeScript as the language, TTK still creates the code in JavaScript

### ISSUE THREAD

**Issue by AE-MS** [OfficeDev/teams-toolkit#12432]
**Describe the bug**
Despite choosing TypeScript as the language when creating a new "Basic Tab," TTK still creates the code as JavaScript in `teamsapp.js`

**To Reproduce**
1. Use TTK to create a new app
2. Choose "Tab"
3. Choose "Basic Tab"
4. Choose "TypeScript"
5. Enter a folder and app name as appropriate

**Expected behavior**
The created app to be authored in TypeScript. In fact, it is still authored in JavaScript.

**Screenshots**
<img width="447" alt="{FB525EB3-AA45-4A28-B67C-5595A7CE279A}" src="https://github.com/user-attachments/assets/85f2df57-4171-4568-a5aa-5b7575ce0185">

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11
 - Version 5.8.1

**CLI Information (please complete the following information):**
I don't know what this section is looking for

**Comment by Yimin-Jin** [comment]
We included a .js file in our TypeScript project because the basic tab is designed to be lightweight and uses HTML to directly access JavaScript. Since browsers don't support TypeScript files directly, we opted for JavaScript here.

**Comment by AE-MS** [comment]
> We included a .js file in our TypeScript project because the basic tab is designed to be lightweight and uses HTML to directly access JavaScript. Since browsers don't support TypeScript files directly, we opted for JavaScript here.

Isn't the user explicitly saying that they want a TypeScript app by choosing the "TypeScript" option when creating the app? If they wanted a JavaScript app they would have selected the "JavaScript" option.

**Comment by Yimin-Jin** [comment]
In designing the Basic Tab, we chose to use JavaScript to keep it lightweight and reduce complexity. Since browsers do not natively support TypeScript files, we would need to compile TypeScript into JavaScript during development, which adds extra build steps and complexity.

**Comment by AE-MS** [comment]
> In designing the Basic Tab, we chose to use JavaScript to keep it lightweight and reduce complexity. Since browsers do not natively support TypeScript files, we would need to compile TypeScript into JavaScript during development, which adds extra build steps and complexity.

I understand the desire to reduce complexity, but isn't the user explicitly saying that they want a TypeScript app by choosing the "TypeScript" option when creating an app?

**Comment by Yimin-Jin** [comment]
@AE-MS Thank you for yor feedback. We are actively investigating feasible solutions to have the core business code in the Basic Tab TS template as TypeScript files. If you have any suggested approaches, we would greatly appreciate your input.

**Comment by Yimin-Jin** [comment]
[](url)
