### ISSUE TITLE
⚠️ TTK Warnings when building Tab projects with AzFunc backend (Tab > React w/ Fluent UI) 🚨 Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/teams-toolkit#12444]
**Describe the bug**
When building a new project using the **Tab > React w/ Fluent UI > TypeScript** template, the **Start Frontend** task throws a few warnings. All are related to dependency **@fluentui/react-window-provider**

I realize this implies a missing file from a failed/suspect NPM install, but I've observed this behavior multiple times on 5 different machines (3 MacOS, 2 Windows).

I observe when this happens on Windows, the TTK doesn't launch a browser window when debugging, but the user can manually open the browser, manually upload the app, and start testing. This does not happen on MacOS.

<details>
  <summary>Click to view errors ❌ in the terminal window output from **Start Frontend**</summary>

```console
WARNING in ./node_modules/@fluentui/react-window-provider/lib/WindowProvider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ac/_play/TeamsTabs01/node_modules/@fluentui/react-window-provider/src/WindowProvider.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ac/_play/TeamsTabs01/node_modules/@fluentui/react-window-provider/src/WindowProvider.tsx'

WARNING in ./node_modules/@fluentui/react-window-provider/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ac/_play/TeamsTabs01/node_modules/@fluentui/react-window-provider/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/ac/_play/TeamsTabs01/node_modules/@fluentui/react-window-provider/src/index.ts'

WARNING in ./node_modules/@fluentui/react-window-provider/lib/version.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ac/_play/TeamsTabs01/node_modules/@fluentui/react-window-provider/src/version.ts' file: Error: ENOENT: no such file or directory, open '/Users/ac/_play/TeamsTabs01/node_modules/@fluentui/react-window-provider/src/version.ts'
```
</details>

**To Reproduce**
1. Create a new project using the **Tab > React w/ Fluent UI > TypeScript** template
2. Start debugging using the **Run & Debug > PLAY**
3. Watch for the **Start Frontend** terminal window open & start
4. Open **Start Frontend** terminal and observe errors.

**Expected behavior**
The task **Start Frontend** runs without warnings.

**Screenshots**
n/a

**VS Code Extension Information (please complete the following information):**
 - OS: MacOS v14 & v15
 - Version: v5.8.1

**CLI Information (please complete the following information):**
 - OS: MacOS v14 & v15
 - Version: v3.0.2

**Additional context**
n/a

**Comment by Yimin-Jin** [comment]
Thank you for your feedback. This issue has already been mentioned here: [React with Fluent UI Tab Error](https://github.com/OfficeDev/teams-toolkit/issues/12261). It does not prevent the template from starting normally, and we have already fixed it in the prerelease version.

**Comment by andrewconnell** [comment]
@Yimin-Jin said:
> we have already fixed it in the prerelease version

WRT to the "prerelease version", are you referring to the VSC TTK extension or in the templates?

**Comment by Yimin-Jin** [comment]
@andrewconnell. We will address this issue in the next pre-release version of the TTK. Additionally, I'd like to note that this is only a warning-level log and it does not prevent the template from starting correctly.

**Comment by andrewconnell** [comment]
Not sure if you want to leave this open until it's resolved for others to see if they run into it, or close it... but feel free to close this issue if you please.
