### ISSUE TITLE
TeamsActivityHandler not working when debugging locally in VS Code since upgraded to Mac Sequoia

### ISSUE THREAD

**Issue by pjm4** [OfficeDev/teams-toolkit#12475]
**Describe the bug**
Since I've upgraded to Mac Sequoia yesterday, I haven't been able to receive a welcome message when debugging locally.

**To Reproduce**
1. Upgrade your Mac to Sequoia
2. Create a sample Chat Notification Message bot 
----------------------------------------------------------------------
3. Select Teams Toolkit from the Activity Bar
4. Under Development section select Create New App
5. Select Bot
6. Select Chat Notification Message
7. Select HTTP Trigger Azure Functions
8. Select Typescript
9. Select Default Folder /Users/`<username>`/TeamsApps
10. Give it a name e.g. testbotmessage
----------------------------------------------------------------------
11. In VS Code Teams Toolkit, log in to Azure with a subscription (mightn't be necessary) 
12. In VS Code Teams Toolkit, log in to Microsoft 355
13. Select Run and Debug on Activity Bar and select Debug in Teams (Edge or Chrome)
14. Wait for the browser to start up and log in with the same 365 account that was used in step 12 above.
15. The notification bot install screen will display, select Add
16. It creates a new chat for the notification bot, however, **no welcome message is displayed**.

**Expected behavior**

A welcome message should be displayed after installing the Chat Notification Message bot.

**VS Code Extension Information (please complete the following information):**
 - OS: Mac
 - Version: v5.9.2024091807 (pre-release) also occurs with latest stable release

**CLI Information (please complete the following information):**
node --version
v20.9.0
npm --version
10.1.0

**Additional context**
`this.onInstallationUpdateAdd` doesn't work either, so it looks like the `TeamsActivityHandler` is not working properly at all.
I went to my Windows 11 machine and using the above steps, the Chat Notification Bot displays the Welcome message on install as expected.

There is chat online about how Mac Sequoia has made some changes to their security. I wonder if the mDNSResponder mentioned here https://support.apple.com/en-us/121238 could be affecting this?

**Comment by swatDong** [comment]
Debugging starts Dev Tunnels to expose your local bot endpoint publicly.
Please check if any error shown on the "Start local tunnel" task terminal, which may look like:
<img width="653" alt="image" src="https://github.com/user-attachments/assets/c53c17d0-cb44-49ac-9566-5b1906a2b735">


cc @lijie-lee for this local debugging issue.
