### ISSUE TITLE
Error: Unable to execute dev tunnel operation 'start-host'. Tunnel service returned status code: 403 Forbidden

### ISSUE THREAD

**Issue by raymondilife** [OfficeDev/teams-toolkit#12487]
**Describe the bug**
[2024-10-06T22:37:01.395Z] [Info] - Current VS Code locale is: en-us
[2024-10-06T22:37:01.486Z] [Info] - Teams Toolkit extension is now active!
[2024-10-06T22:38:25.472Z] [Info] - Running 'Validate prerequisites' Visual Studio Code task.

(Total: 3 Steps) Teams Toolkit is checking the required prerequisites.

(1/3) Checking Node.js ...
(2/3) Checking Microsoft 365 Account ...
(3/3) Checking ports occupancy ...

Summary:

(√) Done: Node.js version (v18.20.4) is installed 
(√) Done: Microsoft 365 Account (DCP20140014@daelimcloud.com) is logged in and custom app upload permission is enabled 
(√) Done: Ports (3978, 9239) are not occupied 

Visit https://aka.ms/teamsfx-tasks/check-prerequisites to get more info about 'Validate prerequisites' task.

[2024-10-06T22:38:26.265Z] [Info] - Finished 'Validate prerequisites' Visual Studio Code task in 0.80 seconds.
[2024-10-06T22:38:26.286Z] [Info] - Running Visual Studio Code task: 'Start local tunnel'

(Total: 1 Step) Teams Toolkit is starting local tunneling service to forward public URL to local port. Open the terminal window for details.

(1/1) Starting dev tunnel service ... 

Summary:

(×) Error: Unable to execute dev tunnel operation 'start-host'. Tunnel service returned status code: 403 Forbidden

Visit https://aka.ms/teamsfx-local-tunnel-task to get more info about 'Start local tunnel' task.

**To Reproduce**

**Expected behavior**

**Screenshots**
![vscode1](https://github.com/user-attachments/assets/cebd0654-24fe-4424-841d-6e91bdd09284)

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**
Version: 1.94.0 (user setup)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
**Additional context**

**Comment by lijie-lee** [comment]
Hi @raymondilife 

To figure out why this issue happened, could you please share two more information?
- What is the definition of "Start local tunnel" task. It is located in the file `.vscode/tasks.json` with label name **Start local tunnel**
- what the response would be if you execute the command `devtunnel user login` with your M365 accout in your terminal. (From the http status code 403 provided by you, I think there is some permission issue when login devtunnel)

Thanks.
