### ISSUE TITLE
"Create and configure the app manually" error message doesn't provide help on how to do that

### ISSUE THREAD

**Issue by AE-MS** [OfficeDev/teams-toolkit#12486]
**Describe the bug**
If I try to run an app in TTK, I get this error message:
```
[Error] - code:AadAppClient.ClientSecretNotAllowed, message: Your tenant doesn't allow creating a client secret for Microsoft Entra app. Create and configure the app manually. Alternatively, you can skip this step by choosing the 'Debug in Test Tool' option.
 Help link: https://aka.ms/teamsfx-actions/aadapp-create
```

Unfortunately, the link isn't actually helpful. If you go to that link, it doesn't tell you how to create and configure the app manually. Even if you go to the "ClientSecretNotAllowedError" section of the page, the "solution" it provides is:

"Solution: Check the application policies and possibly alter the approach to authentications."

That is not helpful as I don't know how to "check the application policies" and I don't know what are other "approaches to authentications" that I should be considering. Also it should be "authentication" (singular).

**Expected behavior**
If the error is blocking (it is) and it provides help, then the help should actually tell you how to work around/fix the blocking problem.

**Comment by frankqianms** [comment]
Hi @AE-MS, 
Thank you for your feedback. We will take a look soon. 
Since we are in Chinese National Day vacations between 10/1 to 10/7, please expect delays for response.  
Thank you very much~

**Comment by blackchoey** [comment]
@AE-MS Thanks for the feedback. I have updated the wiki to better explain how to solve the error. Also paste the solution here:

Option 1: You can create a [M365 developer tenant](https://developer.microsoft.com/en-us/microsoft-365/dev-program) and login to that tenant to continue development.

Option 2: You can create an app with the help of your tenant admin and follow below documents to configure it:

* Use an existing Entra app for SSO: https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision#use-an-existing-microsoft-entra-app-for-your-teams-app
* Use an existing Entra app for your bot: https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision#use-an-existing-microsoft-entra-app-for-your-bot
