### ISSUE TITLE
Upgrade the Teams AI package dependency in AI Chat Bot templates for VS 17.11

### ISSUE THREAD

**Issue by therealjohn** [OfficeDev/teams-toolkit#12493]
17.11.4 has an old Teams AI lib dep in the template and needs bumped to support the latest AI features like citations, feedback, etc.

![image](https://github.com/user-attachments/assets/0a450205-79cb-47c2-955c-068dfddc6e71)

**Comment by xzf0587** [comment]
Hi @therealjohn,
Thanks for reaching out.
We are going to upgrade the Teams AI package version to `1.5.*` for all templates in VS 17.12.
And there will be more templates for Teams AI in VS 17.12 as well.
