### ISSUE TITLE
Running rerequesites checks an error message appears

### ISSUE THREAD

**Issue by Ringo-code-droid** [OfficeDev/teams-toolkit#12517]
Unable to run the environment prerequesites issue

**Comment by Ringo-code-droid** [comment]
[Error] - code:Ext.PrerequisitesValidationError, message: Prerequisites check was unsuccessful. To bypass checking and installing prerequisites, disable them in Visual Studio Code settings. Please check the Output panel to see the details.
 Help link: https://aka.ms/teamsfx-get-started-prerequisite

**Comment by lijie-lee** [comment]
Hi @Ringo-code-droid, Thanks for reaching out

Could you share more info about this issue? 
- which template or sample you used
- the version of teams toolkit and the version of node you userd.
