### ISSUE TITLE
findChannel taking minutes with only around 100 items in the storage

### ISSUE THREAD

**Issue by tinsheep** [OfficeDev/teams-toolkit#12563]
**Describe the bug**
As the conversation store grows, in order to search the store is taking a minute or more to return across all my environments

**To Reproduce**

1) Load your azure blob storage (StorageV2 (general purpose v2)) with 50- 100+ records from personal and channel conversationTypes and tenants and attempt to retrieve a specific channel id, e.g.
`    try {
      channel = await notificationApp.notification.findChannel(c => Promise.resolve(c.info.id === requestBody.channelId));
`
2) observe that the call can take a minute or more to retrieve the channel

**Expected behavior**

I would expect the findChannel to return in seconds with a relatively small number of records.

**Screenshots**

**VS Code Extension Information (please complete the following information):**
Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
TeamsFx version - 2.3.2

**Additional context**
I was having a similar problem with getPagedInstallations and when I followed the guidance for setting the validationEnabled to false on the 2.3.2 fx version that really improved performance. Is there similar checking going on here or anything I can do to speed things up? I'm very thankful for this library so thank you for all the work, but, the time it takes for this call is not reasonable IMO.

**Comment by swatDong** [comment]
The `findChannel` underlying calls `getTeamDetails` on each team. So if you have a few of teams, it's expected to take longer to iterate all teams.
One recommendation is cache the channel then use it later.

Ref:
- https://github.com/OfficeDev/teams-toolkit/blob/dev/packages/sdk/src/conversationWithCloudAdapter/notification.ts#L718
- https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=typescript#get-teams-details

**Comment by tinsheep** [comment]
Thank you - it sounds like there is nothing you can do, but, to help me understand I'm passing in the channelId and that is in the conversation store and so why is it necessary then to getTeamDetails on every team? I was told to just install the app to the general channel so it shouldn't have to iterate through all the channels, correct?  A couple of my teams has over 80 channels - dunno if that has a performance hit or not. 

And as far as caching the channel I never know when it will be needed and I'm thinking that is the point of having the conversation store?

Thanks for the continued help,
mp

**Comment by swatDong** [comment]
`findChannel` can get another channel rather than the installed general one, thus including remote calls.

If you are exactly matching the channelId in conversation store, how about just iterating the store to get the `ConversationReference`? E.g.,
``` typescript
for (const ref of /*your-store*/) {
  if (ref.channelId == requestBody.channelId) {
    const target = new TeamsBotInstallation(adapter, ref, botId);
    await target.send...
  }
}
```

**Comment by tinsheep** [comment]
Thank you - this sounds like what I should do. I just need help with the 
for (const ref of /*your-store*/) part
I know how to get the installations with the notificationApp.notification.getPagedInstallations( but then I would not need to new up the TeamsBotInstallation like you are doing so there must be a way that I am missing - appreciate the help!

**Comment by swatDong** [comment]
To exactly match via `getPagedInstallations`, try this:
```typescript
const installations = ... getPagedInstallations ...
for (const target of installations) {
  const ref = target.conversationReference;
  if (ref.channelId == requestBody.channelId) {
    await target.send...
  }
}
```
