### ISSUE TITLE
Tenant ID Issue while Deploying the frontend code through Microsoft Teams Toolkit 

### ISSUE THREAD

**Issue by nileshganvir41** [OfficeDev/teams-toolkit#12589]
We are deploying our frontend code through Microsoft Teams Toolkit. Our Azure resources was created in the Different Tenant id and our Microsoft Teams toolkit tenant is different. So while deploying our frontend code through Microsoft Teams Toolkit we will getting error. For Error please check snap that we have attached.

We want to deploy our code using Teams Toolkit using our current Tenant ID which is start with '9c0e74bf-63ad-4d83-802c-30dfa888859a'.

[Doc1.docx](https://github.com/user-attachments/files/17510919/Doc1.docx)

**Comment by Siglud** [comment]
Your M365 account is totally unrelated to your Azure account or tenant. 
The deployment process will only depend on your Azure account and ignore any tenant information, if your Azure account have enough right to operate the Azure resource you want to deploy to, then you can finish the deployment whatever the resource placed in any tenant. 
The `TEAMS_APP_TENANT_ID` is only related to your M365 account and the Teams App, not your Azure resource. So, you should rollback your change to this env value and try run deploy again.
