### ISSUE TITLE
teamsapp in CI: asking for authentication even after login

### ISSUE THREAD

**Issue by half2me** [OfficeDev/teams-toolkit#12595]
**Describe the bug**
I'm running `teamsapp`  as part of a CI run.
```
# node:lts
- npm i -g @microsoft/teamsapp-cli
- teamsapp --version
- teamsapp auth login azure --interactive false --service-principal -u $AZURE_ORG_APP_ID -p $AZURE_ORG_PASSWORD --tenant $AZURE_ORG_TENANT_ID
- teamsapp auth list
- teamsapp provision --interactive false --env production
 ```
The login seems to succeed, but the provision step still asks for me to login again. Even though I've set `--interactive false` its still trying to open `xdg-open`.

**Screenshots**
![Screenshot 2024-10-25 at 18 03 41](https://github.com/user-attachments/assets/21e6945e-092a-4ac5-8a85-40f113a03b88)
![Screenshot 2024-10-25 at 18 05 04](https://github.com/user-attachments/assets/c65bc953-34c4-4ac0-b129-3ce96eb6bab4)

**CLI Information (please complete the following information):**
 - OS: linux (docker)
 - Version `node:lts`

**Additional context**

**Comment by jayzhang** [comment]
@half2me  The output tells that you are required to login m365 account before provision. You can set the two enviornment variables: "M365_ACCOUNT_NAME" and "M365_ACCOUNT_PASSWORD" and try again.

**Comment by half2me** [comment]
@jayzhang how would that work if I have 2FA enabled?
