### ISSUE TITLE
Declarative Agent got "Sorry, I can't chat about this. To Save the chat and start a fresh one, select New chat." even though the API call was successfully

### ISSUE THREAD

**Issue by frankchen76** [OfficeDev/teams-toolkit#12737]
**Describe the bug**
I used MS Teams Toolkits to create a project and call a REST API to get a ticket list. After I provisioning to the Copilot tenant, I got the "Sorry, I can't chat about this. To Save the chat and start a fresh one, select New chat." even though the API call was successfully via "Show Plugin developer info". can you share how we can troubleshooting the issue?

**To Reproduce**
1. Used MS Teams toolkit to start a Declarative Agent project
2. Added an API plugins by pointing to an API document
3. Went to MS Teams toolkit extension to provisioning the agent to Copilot tenant. 
4. Executed prompt to trigger the API call. 

**Expected behavior**
Once the API is called successfully, the result should be displayed correctly. 

**Screenshots**
the error message: 
![image](https://github.com/user-attachments/assets/4a936e94-c904-474c-8efa-7aec8c7eca70)

the developer info showed API was called successfully
![image](https://github.com/user-attachments/assets/9e0e5d26-77fa-4da7-84cc-8a5ce8442d81)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11
 - Version: 5.10.0

**Comment by anchenyi** [comment]
hi @frankchen76 , thanks for reporting this. Could you share your .zip app package for further investigation?

**Comment by anchenyi** [comment]
Hi @frankchen76, it’s okay to return more than 3 items in the plugin API. Based on the description, it seems more likely that the issue is due to the content itself, which might violate some policies. @MuyangAmigo could you help let the platform team check this issue first?

**Comment by frankchen76** [comment]
@anchenyi, thanks for your note. I felt about the same way. But when I reviewed those contents ```"title": "Creating a Jira connector","description": "Need help with creating a Jira connector on server xyz. I cannot find information from knowledge base"```, it seems there is no harmful language there. Are there any documents mentioned those policies? If we have such content returned from API, what would be the guidance to make sure it meets the Copilot's "Policies"? I am a MSFT, feel free to ping me via alias tachen from MS Teams if you need more information. Thanks

**Comment by MuyangAmigo** [comment]
Hey @frankchen76 I will reach in Teams.

**Comment by swaminawale** [comment]
I’m facing a similar issue when calling the Graph API to retrieve specific user details from their profile. The prompts I’m using are:
  **"conversation_starters": [
    {
      "text": "Retrieve the profile information of the signed-in user.",
      "title": "Get my details"
    },
    {
      "text": "Give me work location of [person name]",
      "title": "Get work location"
    }
  ]**

Interestingly, this issue is inconsistent. Sometimes the prompts work as expected and return the correct details, but other times I get the error:
'Sorry, I can't chat about this. To save the chat and start a fresh one, select New chat.'

I was able to successfully provision this agent after addressing some RAI-related issues earlier (modifying certain terms that were flagged during provisioning). However, now this intermittent behavior is causing confusion.

Any insights or debugging tips would be greatly appreciated @frankchen76  @MuyangAmigo !

**Comment by frankchen76** [comment]
Hi @swamisnawale, when you enabled [Debug an agent with developer mode](https://learn.microsoft.com/en-us/microsoft-365-copilot/extensibility/debugging-copilot-plugin), what the status code did you see for your API call? Did you see 200 status code or something else?

**Comment by swaminawale** [comment]
Hi @frankchen76 , status code is 200 OK from the response
