### ISSUE TITLE
Provisioning of declarative agent stopped working

### ISSUE THREAD

**Issue by benedikt-udg** [OfficeDev/teams-toolkit#12781]
**Describe the bug**
As of this morning (Monday, 25 November 2024, roughly 9:00 UTC), provisioning of declarative agents stopped working for me. It did work earlier this morning. However, no change was made on my side to the agent code. Also there is no error message in the provisioning output (see below).

**To Reproduce**
1. In Teams Toolkit click "Create new app"
2. Click "Agent" -> "Declarative Agent" -> "No Plugin" (though it doesn't seem to matter if it has a plugin or not)
3. Choose a name, e.g. "Debug Declarative Agent"
4. Click "Provision".
5. Switch to https://www.office.com/chat/?auth=2
6. The agent "Debug Declarative Agent" does not appear in the list of agents

**Expected behavior**
The agent "Debug Declarative Agent" appears in the list of agents on https://www.office.com/chat/?auth=2 and can be used.

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 10
 - Version v5.10.0

**Additional context**
This is the provisioning log:
```
[2024-11-25T13:48:18.343Z] [Info] - Executing provision 

Lifecycle stage: provision(5 step(s) in total). The following actions will be executed: 
(1/5) Action teamsApp/create: create Teams app.
(2/5) Action teamsApp/zipAppPackage: build Teams app package.
(3/5) Action teamsApp/validateAppPackage: validate Teams app.
(4/5) Action teamsApp/update: update Teams app.
(5/5) Action teamsApp/extendToM365: acquire Microsoft 365 title with the app package

[2024-11-25T13:48:18.344Z] [Info] - Executing lifecycle provision
[2024-11-25T13:48:18.530Z] [Info] - (√)Done: Teams Package c:\Users\...\Code\debugging-declarative-agent\appPackage\build\appPackage.dev.zip built successfully!
[2024-11-25T13:48:18.731Z] [Info] - 
Teams Toolkit has checked against all validation rules:

Summary:
51 passed.



A complete log of validations can be found in c:\Users\...\AppData\Roaming\Code\logs\20241125T142304\window3\exthost\TeamsDevApp.ms-teams-vscode-extension\20241125T134348.log
[2024-11-25T13:49:33.106Z] [Info] - TitleId: U_2fdf38bb-dacf-caa2-1942-da29efdc9626
[2024-11-25T13:49:33.106Z] [Info] - AppId: 064495dc-e1bf-4779-aab1-bf797be78740
[2024-11-25T13:49:33.108Z] [Info] - Finished Executing lifecycle provision. Result: {"TEAMS_APP_ID":"b80c56eb-f891-41a6-9668-98d1fccc627e","TEAMS_APP_TENANT_ID":"6ffe90e7-2d89-47e6-97bf-c03294cf3e63","TEAMS_APP_UPDATE_TIME":"2024-11-25T13:48:21.5666234+00:00","M365_TITLE_ID":"U_2fdf38bb-dacf-caa2-1942-da29efdc9626","M365_APP_ID":"064495dc-e1bf-4779-aab1-bf797be78740"}
[2024-11-25T13:49:33.110Z] [Info] - Execution summary:

Summary:
(√) Done: Lifecycle stage provision was executed successfully.
  (√) Done: teamsApp/create was executed successfully.
    (√) Done: Teams app with id b80c56eb-f891-41a6-9668-98d1fccc627e already exists, skipped creating a new Teams app.
  (√) Done: teamsApp/zipAppPackage was executed successfully.
  (√) Done: teamsApp/validateAppPackage was executed successfully.
  (√) Done: teamsApp/update was executed successfully.
    (√) Done: Teams app b80c56eb-f891-41a6-9668-98d1fccc627e updated successfully
  (√) Done: teamsApp/extendToM365 was executed successfully.
    (√) Done: Microsoft 365 title acquired successfully (U_2fdf38bb-dacf-caa2-1942-da29efdc9626).

[2024-11-25T13:49:33.111Z] [Info] - 5/5 actions in provision stage executed successfully.
```

**Comment by Prasad-MSFT** [comment]
@benedikt-udg, thank you for raising your concern. Could you please let us know if this issue is only specific to you or does it happen with others as well in your organization?

**Comment by anchenyi** [comment]
Hi @benedikt-udg, thanks for reporting this issue. Does the agent appear later? Sometimes, it might take some time for the back-end to process. Does this happen to others in your organization as well?

**Comment by benedikt-udg** [comment]
> Hi @benedikt-udg, thanks for reporting this issue. Does the agent appear later? Sometimes, it might take some time for the back-end to process. Does this happen to others in your organization as well?

Yes, I checked today and the agent has appeared (and so has every other agent that I had previously deleted). But I still cannot update it - at least not directly. Is there any indicator as to how long I would have to wait to get it to update? It's really difficult to develop like this.

I also checked with my colleague who is also working with declarative agents and for her provisioning has stopped as well.

**Comment by anchenyi** [comment]
hi @benedikt-udg , may I know how you update the agent? You need to 'provision' it again to update.

**Comment by benedikt-udg** [comment]
Hello @anchenyi, my workflow is as follows:
- I make my changes to the files in VS Code
- I click provision in the Teams Toolkit plugin inside VS Code
- Provisioning runs through without error and reports `5/5 actions in provision stage executed successfully`
- I refresh the browser on https://www.office.com/chat/?auth=2
But the changes are not deployed. I tried with changing the prompt, changing the API parameters for my plugin or simply only changing the name of the agent, but none of these changes are in effect.

**Comment by benedikt-udg** [comment]
@anchenyi: One additional piece of information: Today, the code that I tried to provision yesterday is available on https://www.office.com/chat/?auth=2. But the problem is that if I provision again now, I again cannot see any new updates I made today.

So it seems there is a time delay of a couple of hours before any of my changes actually show up in Copilot.

**Comment by anchenyi** [comment]
hi @MuyangAmigo ,do you know who to reach out to for this issue? There’s a time delay in the Copilot agents' updates. Also, do we have any indicators to show users when an update has taken effect?

**Comment by MuyangAmigo** [comment]
Hello @benedikt-udg We are checking internally to see if there are any downstream service issues that could have impact on the delay of provisioning your changes.

**Comment by MuyangAmigo** [comment]
Hello @benedikt-udg upon checking internally, there was indeed an issue impacting TTK provisioning changes to Cipilot. Now this should be resolved, please let us know if you continue to experience issues.

**Comment by lucab131** [comment]
Hello @MuyangAmigo, to date I've the same problem of @benedikt-udg. I try to provision my declarative copilot agent, it appears on dev.teams.microsoft.com, it appears in my app management directly in Copilot, but it doens't appear in the right scroll column of applications. After some time it may appears but in this situation development is not possible. Any way to resolve this problem? Thank you.

**Comment by Lasitha-Jayawardana** [comment]
Hello @MuyangAmigo @anchenyi ,

We also have had exactly the same problem as @benedikt-udg for over a month and we still have it even today. The declarative copilot agent either vanishes or is stuck in the previous plugin version (from manifest) most of the times. I am also unable to uninstall the app when it is stuck in previous plugin version. It takes hours and sometimes days to get the latest version of the app back or the app itself back.

VSCode Teams Toolkit Version :` v5.10.1`

We also checked with teams/toolkit pre-release version, but this issue still prevails.
`v5.11.2024112909 (pre-release)`

It has been challenging to make progress on development due to this issue. Could you kindly suggest any possible solutions for now?

**Comment by benedikt-udg** [comment]
> Hello @benedikt-udg upon checking internally, there was indeed an issue impacting TTK provisioning changes to Cipilot. Now this should be resolved, please let us know if you continue to experience issues.

I still have the same problems as reported before. As @lucab131 mentioned, they appear immediately in https://dev.teams.microsoft.com/apps, but not in the right hand sidebar of Copilot so even though they're probably uploaded, I can't use them.

**Comment by claraschneiker** [comment]
We experience the same issue especially since last thursday! Development is not possible for us anymore unfortunately.

**Comment by anchenyi** [comment]
hi @claraschneiker, thanks for reporting. We are contacting the related team for this delay issue. I will keep this chat updated once I get any possible solutions. Sorry for the inconvenience.

**Comment by TheZalRevolt** [comment]
Here just to say that I got the same problem, `v5.10.1` no update available.
When I try to provision the agent I'm working on, it won't show on the copilot chat page but if I go to the app page I'm able to see the new agent.
This is a screenshot from app page
![image](https://github.com/user-attachments/assets/5e773747-9aea-4aed-b7c7-ff2c2de294a0)
This is a screenshot from my copilot page
![image](https://github.com/user-attachments/assets/8e775670-37ec-4b24-a8e3-de559b9324d8)

**Comment by anchenyi** [comment]
There was an outage of external dependencies, which was resolved 24 hours ago. Please check if the issue still persists. Apologies for the inconvenience.

**Comment by benedikt-udg** [comment]
@anchenyi unfortunately, there is still no change in behavior. The problem still persists.

**Comment by TheZalRevolt** [comment]
By my side seems to be working

**Comment by anchenyi** [comment]
hi @benedikt-udg , I saw the issue has been resolved for some users now. Could you retry again? If still persists, could you provide your microsoft account name for further investigation? Thanks!

**Comment by lucab131** [comment]
Thank you guys, the problem is solved for me too. :)

**Comment by shemogumbe** [comment]
This is still an issue on my side,
provisioning an agent is succesful on visual studion, however the agent is not visible under agents panel.
Some time even the agents panel is not visible.

If a waiting period exists, how long could it be, How do I resolve this.

The agent exists in https://dev.teams.microsoft.com/apps, but even from there when I click preview in teams, it says app not found, sometimes it exists, I add it to teas and it disappears, doesn't appear in the chats

**Comment by anchenyi** [comment]
Replied in Teams.

**Comment by anchenyi** [comment]
> This is still an issue on my side, provisioning an agent is succesful on visual studion, however the agent is not visible under agents panel. Some time even the agents panel is not visible.
> 
> If a waiting period exists, how long could it be, How do I resolve this.
> 
> The agent exists in https://dev.teams.microsoft.com/apps, but even from there when I click preview in teams, it says app not found, sometimes it exists, I add it to teas and it disappears, doesn't appear in the chats

Replied in Teams.
