### ISSUE TITLE
Quite challenging to create teams metadata package for existing bot

### ISSUE THREAD

**Issue by zikalino** [OfficeDev/teams-toolkit#3364]
**Is your feature request related to a problem? Please describe.**

I have created a bot that is already deployed to Azure. What I would like to do is to just create "teams metadata package" for that existing bot.

In order to do that I have tried to create a bot based on example, and then just compare **localSettings.json** with generated infrastructure, and update **localSettings.json** with my existing bot parameters accordingly and then just generate the package.

Unfortunately I have failed to create Azure bot infrastructure using **Provision to the cloud** option (added another issue for that), so parameters in **localSettings.json** are empty.

In result I don't really know what parameters are important, and how they actually match into my existing bot infrastructure.

I think it's quite important to resolve this problem, as the extension doesn't support all possible languages. In my case I have created a bot using **Bot Framework Composer** and I am developing it in Python.

**Describe the solution you'd like**

It would be good to:

(1) have detailed description on how to use existing bot configuration
(2) or an option "use existing azure resources", where I could select existing bot and extension would simply fetch all the information needed and populate **localSettings.json**

If somebody could help me to configure my existing bot, I would be happy to contribute solution (2)

**Comment by MuyangAmigo** [comment]
Hello @zikalino. Seems like you are developing a Bot in Python using Bot Framework and directly deployed it to Azure and just want to make sure your bot also runs in Teams as well? If this is the case, while we don't have direct support to configure such an existing bot in Teams Toolkit right now, I think what makes sense to do is:
* Make sure Teams channel is enabled in Bot Channel Registration in Azure Portal.
![image](https://user-images.githubusercontent.com/11220663/146300566-5678efe3-c469-485c-b4d2-8f2945c1da36.png)

* Create a new teams app via [Teams Developer Center](dev.teams.microsoft.com) and configure that app with your existing bot id.
![image](https://user-images.githubusercontent.com/11220663/146301332-b9bb271e-2f13-4258-88be-1b7e5d4b778c.png)

* With the above setup, you will be able to generate a teams app package with the metadata you needed to test out the app.
![image](https://user-images.githubusercontent.com/11220663/146301264-4766f6a2-ae1e-4ff6-b038-b08edfdf9965.png)

We will consider how to better support your scenario with the Teams Toolkit in the future. Thanks for your feedback!

**Comment by zikalino** [comment]
Hi @MuyangAmigo Thanks a lot for help!

Now I have my bot published, and also approved by my admin.

Unfortunately I am still not able to do it quite right:
- my bot works correctly via webchat
- there are no reported problems in teams channel configuration in Azure Portal
- my bot appears online (green) in my teams application on the phone, i can send messages to the bot but not getting any answers
- the bot appears disabled in my desktop application, sometimes i can send messages to the bot, sometimes i can't
- i have tried to republish the bot via Developer Portal, but I am getting only "Failed to submit this app" -- there's no other diagnostic application, just this message, so it's really hard to figure out what's going on.

How can I figure out / diagnose what is the actual status of my bot and what else needs to be done / fixed?

**Comment by zikalino** [comment]
![image](https://user-images.githubusercontent.com/11562540/146489581-ee93df93-1332-4b93-9c4d-cb7a817dcbbb.png)

**Comment by MuyangAmigo** [comment]
Hey @asnow003 , @zikalino is having issues where he cannot find the app under `app catalog` for his organization after he successfully published app and get approved by Admin. Would this be something you or your team can help take a look with and recommend how to resolve the issue? Thanks a lot!

**Comment by zikalino** [comment]
@asnow003 could you help?

**Comment by MuyangAmigo** [comment]
Hi @zikalino, sorry about the late reply. If you are still experiencing the issue, it would be better to request a support ticket via the "Help" channel from Teams (located on the bottom left sidebar), and select the `report a problem`. In the popup window you can choose the option `Platform - Apps` so this may get your issue routed to a better team. Sorry about the inconvenience.

![image](https://user-images.githubusercontent.com/11220663/149738133-4d602be4-0675-4a2c-a01c-bfcd9dbdaefd.png)

**Comment by MuyangAmigo** [comment]
Addressed in the latest Teams Toolkit.
