### ISSUE TITLE
(TeamsFx) Teams toolkit tab app SSO not working in mobile platform.

### ISSUE THREAD

**Issue by pjpraveenjayakumar** [OfficeDev/teams-toolkit#7574]
**Describe the bug**
Toolkit default sample tab app SSO is deployed. Once tab app loaded, user clicks on "Authorize" button to give the consent. Once consent granted, person control loaded logged in user name and details. If the user logout/login in desktop/web teams user is not required to click on "Authorize" button to load person component. But in mobile, person component is not loading the details. Once user clicks on "Authorize" button in mobile, user has to login in popup and then popup closing. Subsequently person component is loading.
![image](https://user-images.githubusercontent.com/109327327/214093775-4917048f-938b-45fb-afb4-04968e2bcd55.png)

![image](https://user-images.githubusercontent.com/109327327/214096575-36c84b39-f233-4a4e-b92c-619dc1f60ab8.png)

Could you please check and confirm why user has to authorize in mobile again? and it's not the same case with desktop/web client.

we tried to get the fiddler traces but have challenges.

**To Reproduce**
1. deploy the tab SSO toolkit sample.

2. open the same Tab SSO toolkit sample App in mobile (android or iOS ).

3. click on "authorize" button and t will open login popup then provide same credentials then it will load logged in user details in people picker component. 

4. logout and login back from teams mobile and go to respective app. click on "autherize" button and it will again open login popup to enter credentials. it should not be the case like every time it's asking user to enter credentials.

**Expected behavior**
If the user logout/login in desktop/web teams user is not required to click on "Authorize" button to load person component. It should load the person component automatically since SSO has been implemented.

**VS Code Extension Information (please complete the following information):**
 - OS: iOS, Android.
 - Version [iOS 16.2 Android 11]

**Additional context**

**Comment by SLdragon** [comment]
Hi, @pjpraveenjayakumar , thank you for submitting this issue, and sorry for the inconvenience. 

The token is stored in the session storage, so first make sure your browser is not in `private mode` and support session storage. 

And you can call teamsUserCredential.getToken(scope) method to check whether there is an error message here: https://github.com/OfficeDev/TeamsFx/blob/dev/templates/tab/ts/default/src/components/sample/Graph.tsx#L17

PS: by the way, it is not secure to share your password in this public issue page, and make sure to change your password ASAP.

**Comment by KennethBWSong** [comment]
@SLdragon I think it's a limitation of Teams mobile client. @blackchoey Do you remember we have a discussion on this problem before?

**Comment by frankqianms** [comment]
@SLdragon @KennethBWSong As @huimiu and I investigated before, this problem differs in different mobile platforms. Sometimes the login page will continuously popup and cannot successfully consent. It is as if the authorization information is never cached in this issue.

**Comment by KennethBWSong** [comment]
@frankqianms Actually I think this is different from consent issue. This issue will occur when the Tab app failed to silently login, mainly with this [error](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#monitor_window_timeout). I remember there is an issue saying Teams mobile client has some limitation on silent login, and I am working on this.
For consent issue, you need to use an [external auth flow](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider).

**Comment by SLdragon** [comment]
@KennethBWSong , @frankqianms , I checked the github issue, may be related to this comment: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3329#issuecomment-811825340

**Comment by pjpraveenjayakumar** [comment]
@SLdragon Could you please let us know if there any workaround to make it work in mobile platforms ?

**Comment by frankqianms** [comment]
Hi @pjpraveenjayakumar , we have been working on this. Currently, we think it is related to monitor_window_timeout error, and here is the workaround for this error: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#monitor_window_timeout:~:text=To%20solve%20this%20problem%20you%20should%20ensure%20that%20the%20page%20you%20use%20as%20your%20redirectUri%20is%20not%20doing%20any%20of%20these%20things%2C%20at%20the%20very%20least%2C%20when%20loaded%20in%20a%20popup%20or%20iframe.%20We%20recommend%20using%20a%20blank%20page%20as%20your%20redirectUri%20for%20silent%20and%20popup%20flows%20to%20ensure%20none%20of%20these%20things%20can%20occur. You can try it to check if it works for you.
As most of my teammates are in the vacation of Chinese New Year, we will provide you a complete workaround as soon as possible after 1/27.
Sorry for the inconvenience.

**Comment by SLdragon** [comment]
> Could you please let us know if there any workaround to make SSO to work in mobile platforms?

Currently there is no easy workaround to make it work in mobile platform, because TeamsFx SDK doesn't expose the cache location settings. Please stay tuned and we will let you know when we have a solution, thank you!

**Comment by pjpraveenjayakumar** [comment]
Hi @SLdragon Could you please let us know if there is any update ? Thanks

**Comment by KennethBWSong** [comment]
Hi @pjpraveenjayakumar We are confirming with `msal-browser` team about this issue and will reach out to you as soon as we have any update. Thanks!

**Comment by pjpraveenjayakumar** [comment]
hi @KennethBWSong Could you please let us know if there is any update on this? Thanks

**Comment by pjpraveenjayakumar** [comment]
hi @KennethBWSong  and @SLdragon kindly let us know if there is any update or when it can be fixed and available for public ring. it's little urgent for customers since the SSO app has been already moved to production and live. thanks for understanding and looking forward to your response.

**Comment by SLdragon** [comment]
Hi, @pjpraveenjayakumar , sorry for the late. From our testing, this issue is caused by MSAL.js v2 (@azure/msal-browser) library and getAccountByUsername inside this library return null on IOS platform. Maybe related to some IOS webview limitation cased this issue, and we have already created an issue here: 
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5617

We are waiting for the response from MSAL teams, will let you know when there is a solution, thanks!

**Comment by ThomasPe** [comment]
still broken for me with the latest npm updates. Any news?

**Comment by ThomasPe** [comment]
How does this issue not have a higher priority? Not being able to log into the app on iOS means you cannot publish the app to the Teams Store as it does not pass the inspection. 

I just tried the latest preview on Static Web Apps and it still does not work! The toolkit has basically been unsuable for over a year due to this if you want to distribute your app through the Teams Store.

**Comment by KennethBWSong** [comment]
Hi @ThomasPe Thank you for using our Toolkit. We would recommend you have a try with "React with Fluent UI" template for apps cross platforms. You can simply click on "Create a new app" -> "Tab" -> "React with Fluent UI" to create this app.

This template implements OBO flow which is recommended by Teams team. This template works well on IOS platform in our test.

**Comment by ThomasPe** [comment]
Thanks for the update, it seems this requires iOS to be 17.x or newer?
Btw. is there an updated sample on how to integrate both the API and Microsoft Graph Toolkit?

**Comment by KennethBWSong** [comment]
@ThomasPe This app should not have requirements on the version of iOS, but I only test on latest iOS and Teams. For integration of Teams Toolkit, we don't have a sample now. You can have a try with this [provider](https://learn.microsoft.com/en-us/graph/toolkit/providers/teamsfx), and also this [sample](https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/sso-enabled-tab-via-apim-proxy) which use APIM as backend.

**Comment by keeth** [comment]
My teams app also fails Teams Store validation due to this issue.

**Comment by KennethBWSong** [comment]
> I have double checked with a new iOS device. From what I can tell iOS 15 and lower are not working. With 17 the sample worked. However I didn't get it to work for my app despite using basically the same code. I assume that this might be due to me perhaps using a Multi Tenant App Registration? Should I create a new issue for this then?

@ThomasPe For multi-tenant issue, please refer to this [wiki](https://github.com/OfficeDev/TeamsFx/wiki/Multi-tenancy-Support-for-Microsoft-Entra-app). If you have any other questions about multi-tenant, please create a new issue, thanks!

**Comment by KennethBWSong** [comment]
> My teams app also fails Teams Store validation due to this issue.

@keeth Thank you for using our Toolkit. As mentioned above, Teams now recommend to use OBO flow for SSO. You can refer to "React with Fluent UI" template for apps cross platforms. You can simply click on "Create a new app" -> "Tab" -> "React with Fluent UI" to create this app.

**Comment by keeth** [comment]
Hmm actually I may have a different issue.  I was not logging in/out of Teams, but silent token acquisition was failing every time on iOS only. Switching `cacheLocation` from `sessionStorage` to `localStorage` for iOS fixed it.  Unfortunately `teamsfx.TeamsUserCredential` is hardcoded to `sessionStorage` so I had to monkeypatch it for iOS :(.

**Comment by ThomasPe** [comment]
@keeth updating the app-start.html and app-end.html to the latest msal-browser version from the CDN fixed the iOS login issue for me.
see https://github.com/OfficeDev/TeamsFx/issues/10379#issuecomment-1905003489 for more info.

`<script type="text/javascript" src="https://alcdn.msauth.net/browser/2.35.0/js/msal-browser.min.js"  crossorigin="anonymous"></script>`

**Comment by ThomasPe** [comment]
I do need to sign into the app on each launch so it doesn't fix the silent sign in

**Comment by keeth** [comment]
@ThomasPe yeah my app was rejected due to the silent sign-in issue. Like I said above, I fixed silent token acquisition by using `localStorage` instead of `sessionStorage` for iOS.

**Comment by adashen** [comment]
close as there is no more issues.
