### ISSUE TITLE
Provisioning fails with "The endpoint property was not recognized as valid HTTPS URL",

### ISSUE THREAD

**Issue by rachit1503** [OfficeDev/teams-toolkit#7901]
Hi,

I am using the Teams Toolkit in VSCode to provision and deploy my bot to Azure. When I run the provisioning step, I get the following error: 
```
[Error] - code:Solution.FailedToDeployArmTemplatesToAzure, message: [Teams Toolkit] Failed to deploy ARM templates. Resource group name: ##Correct Resource Group Name##. Deployment name: teams_toolkit_deployment
Error message: The long-running operation has failed.
Detailed message: 
{
  "provisionResources": {
    "botProvision": {
      "code": "InvalidTemplateDeployment",
      "message": "The template deployment 'botProvision' is not valid according to the validation procedure. The tracking id is '8cd97e7f-68e5-4b6d-83a1-97acc7bc4547'. See inner errors for details.",
      "details": [
        {
          "details": [
            {
              "code": "InvalidBotData",
              "message": "The endpoint property was not recognized as valid HTTPS URL",
              "target": "botname"
            }
          ]
        }
      ]
    }
  }
}
Get toolkit help from https://aka.ms/teamsfx-arm-help.
```

Any idea what is going on? I am unable to fix this manually.

**Comment by hund030** [comment]
We are facing the same issue, too. 
Here's our findings:
Seems ARM is not able to resolve the expression like `uri('https://${webApp.properties.defaultHostName}', '/api/messages')` anymore.
We are still investigating why but before that, we try to get rid of this kind of expression by split botService and webApp into two bicep files.
You can refer to this PR. https://github.com/OfficeDev/TeamsFx-Samples/pull/700
