### ISSUE TITLE
Teams toolkit tab app SSO is not working inside task module in iOS

### ISSUE THREAD

**Issue by kmhigashioka** [OfficeDev/teams-toolkit#8284]
**Describe the bug**
There are two issues:
1. Using the toolkit sample tab app SSO inside the task module (URL) throwing an error when using an iOS device. Tested this on Android, web, desktop Teams client and they are working fine. The error: `Failed to read your profile. Please try again later. Details: r.ConsentFailed: Consent failed for the scope User.Read with error: This call is only allowed in following contexts: ["content","sidePanel","settings","remove","task","stage","meetingStage"]. Current context: "".`
2. Nothing happens when clicking the "Authorize" button.

**To Reproduce**
1. Deploy the sample tab SSO app (or can use my minimum repro repo https://github.com/kmhigashioka/min-repro-ios-issue)
2. Use the "Personal tab" URL as the task module URL.
3. Open the task module using iOS device.
4. The error message is displayed.
5. Clicking on "Authorize" button is unresponsive.

**Expected behavior**
Similar to Android, web, and desktop client, the user information should be displayed.

**Screenshots**
Issue mentioned on number 1:
![image](https://user-images.githubusercontent.com/5535475/230283151-1a64e56f-4640-41e7-813b-c148be71c086.png)

Issue mentioned on number 2:
https://user-images.githubusercontent.com/5535475/230285098-0b893841-bbec-4354-8fc0-69697e911bee.mp4

**VS Code Extension Information (please complete the following information):**
 - OS: iOS
 - Version iOS 16.3

**Additional context**

**Comment by KennethBWSong** [comment]
Hi @kmhigashioka Thank you for using our Toolkit. We are trying to figure out the reason and will reach out to you as soon as we have any update.

**Comment by kmhigashioka** [comment]
Hi @KennethBWSong thanks for looking into it! By any chance, do you have an update on this? We'll be submitting the app soon and want to know if this will be an issue during the approval process.

**Comment by KennethBWSong** [comment]
@kmhigashioka We think the issue may caused by a bug from `teams-js` and have already raised an issue: https://github.com/OfficeDev/microsoft-teams-library-js/issues/1707. We will keep tracking and get back to you if we have any update.

**Comment by adashen** [comment]
close as it is upstream issue and no more asks.
