### ISSUE TITLE
More documentation on bot development section

### ISSUE THREAD

**Issue by asith-w** [OfficeDev/teams-toolkit#9905]
Would it be possible to provide a comprehensive and detailed tutorial or documentation on bot development part? For instance, while creating a notification bot using a toolkit is excellent for new projects, integrating it into older projects can be quite challenging. Personally, I've had to waste several weeks understanding what actually happening with current code, and it often feels like I'm coding blindly

**Describe the solution you'd like**
It would be immensely helpful to include explanations detailing the toolkit's underlying processes, as well as instructions on how to achieve the same tasks **without relying on the toolkit**

**Comment by sffamily** [comment]
Hi @asith-w 
Your scenario is a typical one we'd like to support, but we want to learn a little more about the scenario so we can offer better assistance. 

Would you please share more or open for a chat on this?
